from enum import IntEnum

class PPI_AD(IntEnum):
   PPI_AD_DOSE_SCHEDULE = 0
   PPI_AD_DOCK_STATUS = 1
   PPI_AD_RING_STATUS = 2
   PPI_AD_TIME = 3
   PPI_AD_WEIGHT_MEAS_RATE = 4
   PPI_AD_IMU_SAMPLE_RATE = 5
   PPI_AD_DOCK_BATT_SAMPLE_RATE = 6
   PPI_AD_RING_BATT_SAMPLE_RATE = 7
   PPI_AD_DOCK_TEMP_SAMPLE_RATE = 8
   PPI_AD_DOSE_EVENT_REPORT = 9
   PPI_AD_DOSE_DATA_POINT = 10
   PPI_AD_DOCK_TEMP_LOG = 11
   PPI_AD_DOCK_WEIGHT_LOG = 12
   PPI_AD_DOCK_CHARGE_STATUS = 13
   PPI_AD_RING_DOCKED_STATUS = 14
   PPI_AD_BL_STATUS = 15
   PPI_AD_DOCK_BATT_LEVEL_LOG = 16
   PPI_AD_RING_BATT_LEVEL_LOG = 17
   PPI_AD_DOCK_DEBUG_LOG = 18
   PPI_AD_RING_DEBUG_LOG = 19

   # Baselining PPIs
   PPI_AD_START_BASELINING = 20
   PPI_AD_BASELINING_FEEDBACK = 21
   PPI_AD_VALIDATE_MED = 22

   # Calibration PPIs
   PPI_AD_START_CALIBRATION = 23
   PPI_AD_CALIBRATION_DATA = 24
   PPI_AD_CALIBRATION_WEIGHT_PRESENT = 25
   PPI_AD_CALIBRATION_FEEDBACK = 26

   # Development Commands
   PPI_AD_DEVELOPMENT_CMD = 27

   PPI_AD_MAX = 28


class PPI_TYPE(IntEnum):
   PPI_TYPE_RQ = 0
   PPI_TYPE_RE = 1
   PPI_TYPE_PUSH = 2
   PPI_TYPE_MAX = 3


class MSG_PROT_TX_PACKET_STATUS(IntEnum):
   MSG_PROT_TX_PACKET_STATUS_NONE = 0
   MSG_PROT_TX_PACKET_STATUS_NEW = 1
   MSG_PROT_TX_PACKET_STATUS_COMPLETED = 2
   MSG_PROT_TX_PACKET_STATUS_WAITING_FOR_ACK = 3
   MSG_PROT_TX_PACKET_STATUS_ERROR = 4
   MSG_PROT_TX_PACKET_STATUS_ABANDONED = 5
   MSG_PROT_TX_PACKET_STATUS_MAX = 6

class MSG_PROT_RX_PACKET_STATUS(IntEnum):
   MSG_PROT_RX_PACKET_STATUS_NONE = 0
   MSG_PROT_RX_PACKET_STATUS_NEW = 1
   MSG_PROT_RX_PACKET_STATUS_PROCESSED = 2
   MSG_PROT_RX_PACKET_STATUS_MAX = 3
