from enum import IntEnum


class PPI_AD(IntEnum):
    PPI_AD_DOSE_SCHEDULE = 0
    PPI_AD_DOCK_STATUS = 1
    PPI_AD_RING_STATUS = 2
    PPI_AD_TIME = 3
    PPI_AD_WEIGHT_MEAS_RATE = 4
    PPI_AD_IMU_SAMPLE_RATE = 5
    PPI_AD_DOCK_BATT_SAMPLE_RATE = 6
    PPI_AD_RING_BATT_SAMPLE_RATE = 7
    PPI_AD_DOCK_TEMP_SAMPLE_RATE = 8
    PPI_AD_DOSE_EVENT_REPORT = 9
    PPI_AD_DOSE_DATA_POINT = 10
    PPI_AD_DOCK_TEMP_LOG = 11
    PPI_AD_DOCK_WEIGHT_LOG = 12
    PPI_AD_DOCK_CHARGE_STATUS = 13
    PPI_AD_RING_DOCKED_STATUS = 14
    PPI_AD_BL_STATUS = 15
    PPI_AD_DOCK_BATT_LEVEL_LOG = 16
    PPI_AD_RING_BATT_LEVEL_LOG = 17
    PPI_AD_DOCK_DEBUG_LOG = 18
    PPI_AD_RING_DEBUG_LOG = 19

    # Baselining PPIs
    PPI_AD_START_BASELINING = 20
    PPI_AD_BASELINING_FEEDBACK = 21
    PPI_AD_VALIDATE_MED = 22

    # Calibration PPIs
    PPI_AD_START_CALIBRATION = 23
    PPI_AD_CALIBRATION_DATA = 24
    PPI_AD_CALIBRATION_WEIGHT_PRESENT = 25
    PPI_AD_CALIBRATION_FEEDBACK = 26

    # Development Commands
    PPI_AD_DEVELOPMENT_CMD = 27

    PPI_AD_CAP_DETECTION_CONFIG = 28
    PPI_AD_CAP_DETECTION_SAMPLE_RATE = 29

    PPI_AD_MAX = 30


class PPI_TYPE(IntEnum):
    PPI_TYPE_RQ = 0
    PPI_TYPE_RE = 1
    PPI_TYPE_PUSH = 2
    PPI_TYPE_MAX = 3

class APP2DOCK_COMMANDS(IntEnum):
   APP2DOCK_COMMANDS_NONE = 0
   APP2DOCK_COMMANDS_ENTER_SHIP_MODE = 1
   APP2DOCK_COMMANDS_ENABLE_DFU = 2 
   APP2DOCK_COMMANDS_RESET_DOCK = 3
   APP2DOCK_COMMANDS_POPULATE_DOCK_PUSH_DATA = 4
   APP2DOCK_COMMANDS_MAX = 5

class MSG_PROT_TX_PACKET_STATUS(IntEnum):
    MSG_PROT_TX_PACKET_STATUS_NONE = 0
    MSG_PROT_TX_PACKET_STATUS_NEW = 1
    MSG_PROT_TX_PACKET_STATUS_COMPLETED = 2
    MSG_PROT_TX_PACKET_STATUS_WAITING_FOR_ACK = 3
    MSG_PROT_TX_PACKET_STATUS_ERROR = 4
    MSG_PROT_TX_PACKET_STATUS_ABANDONED = 5
    MSG_PROT_TX_PACKET_STATUS_MAX = 6


class MSG_PROT_RX_PACKET_STATUS(IntEnum):
    MSG_PROT_RX_PACKET_STATUS_NONE = 0
    MSG_PROT_RX_PACKET_STATUS_NEW = 1
    MSG_PROT_RX_PACKET_STATUS_PROCESSED = 2
    MSG_PROT_RX_PACKET_STATUS_MAX = 3


class CALIBRATION_STATE(IntEnum):
    CALIBRATION_STATE_WAIT_FOR_RING_REMOVAL = 0
    CALIBRATION_STATE_SET_DOCK_WEIGHT = 1
    CALIBRATION_STATE_WAIT_FOR_CALIBRATION_WEIGHT = 2
    CALIBRATION_STATE_CALIBRATING = 3
    CALIBRATION_STATE_STORE_UPDATED_PARAM = 4
    CALIBRATION_STATE_COMPLETE = 5
    CALIBRATION_STATE_ERROR = 6
    CALIBRATION_STATE_MAX = 7


class BASELINING_STATE(IntEnum):
    BASELINING_STATE_WAIT_FOR_RING_REMOVAL = 0
    BASELINING_STATE_SET_DOCK_WEIGHT = 1
    BASELINING_STATE_WAIT_FOR_RING = 2
    BASELINING_STATE_SET_RING_DOCK_WEIGHT = 3
    BASELINING_STATE_WAIT_FOR_BACKEND_VALIDATION = 4
    BASELINING_STATE_SET_LOCAL_MED_UID = 5
    BASELINING_STATE_COMPLETE = 6
    BASELINING_STATE_ERROR = 7
    BASELINING_STATE_MAX = 8

class BATTERY_STATE(IntEnum):
   BATTERY_STATE_SOC_GOOD = 0
   BATTERY_STATE_SOC_LOW = 1
   BATTERY_STATE_CHARGING = 2
   BATTERY_STATE_CHARGING_COMPLETED = 3
   BATTERY_STATE_ERROR = 4
   BATTERY_STATE_MAX = 5

class DEBUG_LEVEL(IntEnum):
   DEBUG_LEVEL_TRACE = 0
   DEBUG_LEVEL_DEBUG = 1
   DEBUG_LEVEL_INFO = 2
   DEBUG_LEVEL_WARN = 3
   DEBUG_LEVEL_ERROR = 4
   DEBUG_LEVEL_CRITICAL = 5
   DEBUG_LEVEL_DISABLED = 6
   DEBUG_LEVEL_MAX = 7


class SW_UNIT_ID(IntEnum):
   SW_UNIT_ID_INVALID = 0
   SW_UNIT_ID_DEBUG = 1
   SW_UNIT_ID_QUEUE = 2
   SW_UNIT_ID_UART_DRV = 3
   SW_UNIT_ID_TWI_DRV = 4
   SW_UNIT_ID_SYSTEM_TIME = 5
   SW_UNIT_ID_IMU_DRV = 6
   SW_UNIT_ID_STATE_MACHINE = 7
   SW_UNIT_ID_BUTTON_DRIVER = 8
   SW_UNIT_ID_MESSAGE_PROTOCOL = 9
   SW_UNIT_ID_SERIALIZER_PROTOCOL = 10
   SW_UNIT_ID_UART_IR_DRIVER = 11
   SW_UNIT_ID_SPI_DRV = 12
   SW_UNIT_ID_DOCK_SOURCE_MANAGER = 13
   SW_UNIT_ID_DOCK_COMMS_DRIVER = 14
   SW_UNIT_ID_RING_COMMS_DRIVER = 15
   SW_UNIT_ID_RING_SOURCE_MANAGER = 16
   SW_UNIT_ID_MAIN_DOCK = 17
   SW_UNIT_ID_GENERAL_CONTROL_DOCK = 18
   SW_UNIT_ID_BLE_CONTROL_DOCK = 19
   SW_UNIT_ID_BATTERY_MANAGER_DOCK = 20
   SW_UNIT_ID_DOSE_SCHEDULER_DOCK = 21
   SW_UNIT_ID_LED_CONTROL_DOCK = 22
   SW_UNIT_ID_BUZZER_DOCK = 23
   SW_UNIT_ID_BLE_CS_DOCK = 24 
   SW_UNIT_ID_BLE_CS = 25
   SW_UNIT_ID_BLE_CONTROL = 26
   SW_UNIT_ID_BMS_NPM1300_DRV = 27
   SW_UNIT_ID_NOTIFICATIONS_MODULE = 28
   SW_UNIT_ID_RING_MANAGER = 29
   SW_UNIT_ID_RTC_PCF85363A_DRIVER = 30
   SW_UNIT_ID_SYSTEM_FSM = 31
   SW_UNIT_ID_ADS1235_DRV = 32
   SW_UNIT_ID_TEMP_DRV = 33
   SW_UNIT_ID_WEIGHT_SENSOR = 34
   SW_UNIT_ID_DOSE_SIZE_DETECTION = 35
   SW_UNIT_ID_DOSE_SIZE_DETECTION_FSM = 36
   SW_UNIT_ID_DOSE_DETECTION_DOCK = 37
   SW_UNIT_ID_NFC_READER = 38
   SW_UNIT_ID_MAIN_RING = 39
   SW_UNIT_ID_DOCK_MANAGER = 40
   SW_UNIT_ID_GENERAL_CONTROL_RING = 41
   SW_UNIT_ID_BATTERY_MANAGER_RING = 42
   SW_UNIT_ID_PROX_SENSOR_TMD2635_DRV = 43
   SW_UNIT_ID_CAP_DETECTION_MODULE = 44
   SW_UNIT_ID_TILT_DETECTION_MODULE = 45
   SW_UNIT_ID_DOSE_DETECTION_MODULE = 46
   SW_UNIT_ID_DOSE_DETECTION_FSM = 47
   SW_UNIT_ID_BLE_CONTROL_RING = 48
   SW_UNIT_ID_BLE_CS_RING = 49
   SW_UNIT_ID_BMS_BQ25150_DRV = 50
   SW_UNIT_ID_NFC_TAG_DRV = 51
   SW_UNIT_ID_NFC_TAG_EEPROM_QUEUE = 52
   SW_UNIT_ID_NFC_READER_DRV = 53
   SW_UNIT_ID_NFC_RFAL_GLUE_DOCK = 54
   SW_UNIT_ID_NFC_MOCK_SERIAL_DRIVER = 55
   SW_UNIT_ID_NFC_UT_MSG_PROT = 56
   SW_UNIT_ID_FLASH_DRV = 57
   SW_UNIT_ID_FILESYSTEM = 58
   SW_UNIT_ID_DOCK_DATA_MANAGER = 59
   SW_UNIT_ID_RING_DATA_MANAGER = 60
   SW_UNIT_ID_APP_MANAGER = 61
   SW_UNIT_ID_FDS_MANAGER_MODULE = 62
   SW_UNIT_ID_BASELINING_FSM = 63
   SW_UNIT_ID_CALIBRATION_FSM = 64
   SW_UNIT_ID_MAX = 65