import {
  BATTERY_LEVEL_T_SIZE_BYTES,
  DOSE_SCHEDULE_T_SIZE_BYTES,
  MAX_DOSES_PER_DAY,
  PpiId,
  PpiType,
  type DoseSchedulePpi,
} from "@/utils/ble/messageProtocolPpi";

import type { QuickActionItem, QuickFlowAction, QuickFlowMeta } from "./types";

export const QUICK_FLOW_ACTIONS: QuickActionItem[] = [
  { key: "TIME_RQ", label: "Time RQ" },
  { key: "TIME_PUSH", label: "Time PUSH" },
  { key: "DOSE_SCHEDULE_RQ", label: "Dose RQ" },
  { key: "DOSE_SCHEDULE_PUSH", label: "Dose PUSH A" },
  { key: "DOSE_SCHEDULE_PUSH_ALT_1", label: "Dose PUSH B" },
  { key: "DOSE_SCHEDULE_PUSH_ALT_2", label: "Dose PUSH C" },
  { key: "DOCK_STATUS_RQ", label: "Dock Status" },
  { key: "RING_STATUS_RQ", label: "Ring Status" },
  { key: "DEVELOPMENT_CMD_RQ", label: "Dev Cmd RQ" },
  { key: "CALIBRATION_DATA_RQ", label: "Calibration Data" },
  { key: "START_CALIBRATION_RQ", label: "Start Calibration" },
  { key: "STOP_CALIBRATION_RQ", label: "Stop Calibration" },
  { key: "CALIBRATION_WEIGHT_PRESENT_PUSH_TRUE", label: "Weight Present" },
  { key: "CALIBRATION_WEIGHT_PRESENT_PUSH_FALSE", label: "Weight Removed" },
  { key: "START_BASELINING_RQ", label: "Start Baselining" },
  { key: "STOP_BASELINING_RQ", label: "Stop Baselining" },
  { key: "VALIDATE_MED_RE_TRUE", label: "Validate Med OK" },
  { key: "VALIDATE_MED_RE_FALSE", label: "Validate Med Fail" },
];

export const DOSE_SCHEDULE_PUSH_PAYLOADS: Record<
  "DOSE_SCHEDULE_PUSH" | "DOSE_SCHEDULE_PUSH_ALT_1" | "DOSE_SCHEDULE_PUSH_ALT_2",
  DoseSchedulePpi
> = {
  DOSE_SCHEDULE_PUSH: {
    medication_type: 0,
    dosage_mg: 2,
    temp_upper_limit_deg_c: 60,
    temp_lower_limit_deg_c: 0,
    temp_avg_window_duration_sec: 1800,
    dose_days_bitfield: 0x7f,
    dose_window_duration_minutes: 30,
    dose_window_count: 4,
    dose_window_start_times_minutes: [630, 840, 1050, 1260].slice(0, MAX_DOSES_PER_DAY),
  },
  DOSE_SCHEDULE_PUSH_ALT_1: {
    medication_type: 1,
    dosage_mg: 5,
    temp_upper_limit_deg_c: 60,
    temp_lower_limit_deg_c: 2,
    temp_avg_window_duration_sec: 900,
    dose_days_bitfield: 0x1f,
    dose_window_duration_minutes: 45,
    dose_window_count: 3,
    dose_window_start_times_minutes: [480, 780, 1200].slice(0, MAX_DOSES_PER_DAY),
  },
  DOSE_SCHEDULE_PUSH_ALT_2: {
    medication_type: 2,
    dosage_mg: 1,
    temp_upper_limit_deg_c: 60,
    temp_lower_limit_deg_c: 4,
    temp_avg_window_duration_sec: 1200,
    dose_days_bitfield: 0x7e,
    dose_window_duration_minutes: 20,
    dose_window_count: 2,
    dose_window_start_times_minutes: [540, 1260].slice(0, MAX_DOSES_PER_DAY),
  },
};

export const QUICK_FLOW_META: Record<QuickFlowAction, QuickFlowMeta> = {
  TIME_RQ: {
    title: "Time Request",
    actionName: "TIME_RQ",
    busyKey: "ppi-time-rq",
    ppiName: "AD_TIME",
    ppiId: PpiId.AD_TIME,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "No payload",
    lenHint: "len=0",
  },
  TIME_PUSH: {
    title: "Time Push",
    actionName: "TIME_PUSH",
    busyKey: "ppi-time-push",
    ppiName: "AD_TIME",
    ppiId: PpiId.AD_TIME,
    typeName: "PUSH",
    typeId: PpiType.PUSH,
    payloadHint: "uint32 unix time",
    lenHint: "len=4",
  },
  DOSE_SCHEDULE_RQ: {
    title: "Dose Schedule Request",
    actionName: "DOSE_SCHEDULE_RQ",
    busyKey: "ppi-dose-schedule-rq",
    ppiName: "AD_DOSE_SCHEDULE",
    ppiId: PpiId.AD_DOSE_SCHEDULE,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "No payload",
    lenHint: "len=0",
  },
  DOSE_SCHEDULE_PUSH: {
    title: "Dose Schedule Push A",
    actionName: "DOSE_SCHEDULE_PUSH",
    busyKey: "ppi-dose-schedule-push",
    ppiName: "AD_DOSE_SCHEDULE",
    ppiId: PpiId.AD_DOSE_SCHEDULE,
    typeName: "PUSH",
    typeId: PpiType.PUSH,
    payloadHint: "dose_schedule_t (preset A)",
    lenHint: `len=${DOSE_SCHEDULE_T_SIZE_BYTES}`,
    payloadPreview: DOSE_SCHEDULE_PUSH_PAYLOADS.DOSE_SCHEDULE_PUSH,
  },
  DOSE_SCHEDULE_PUSH_ALT_1: {
    title: "Dose Schedule Push B",
    actionName: "DOSE_SCHEDULE_PUSH_ALT_1",
    busyKey: "ppi-dose-schedule-push-alt-1",
    ppiName: "AD_DOSE_SCHEDULE",
    ppiId: PpiId.AD_DOSE_SCHEDULE,
    typeName: "PUSH",
    typeId: PpiType.PUSH,
    payloadHint: "dose_schedule_t (preset B)",
    lenHint: `len=${DOSE_SCHEDULE_T_SIZE_BYTES}`,
    payloadPreview: DOSE_SCHEDULE_PUSH_PAYLOADS.DOSE_SCHEDULE_PUSH_ALT_1,
  },
  DOSE_SCHEDULE_PUSH_ALT_2: {
    title: "Dose Schedule Push C",
    actionName: "DOSE_SCHEDULE_PUSH_ALT_2",
    busyKey: "ppi-dose-schedule-push-alt-2",
    ppiName: "AD_DOSE_SCHEDULE",
    ppiId: PpiId.AD_DOSE_SCHEDULE,
    typeName: "PUSH",
    typeId: PpiType.PUSH,
    payloadHint: "dose_schedule_t (preset C)",
    lenHint: `len=${DOSE_SCHEDULE_T_SIZE_BYTES}`,
    payloadPreview: DOSE_SCHEDULE_PUSH_PAYLOADS.DOSE_SCHEDULE_PUSH_ALT_2,
  },
  DOCK_STATUS_RQ: {
    title: "Dock Status Request",
    actionName: "DOCK_STATUS_RQ",
    busyKey: "ppi-dock-status-rq",
    ppiName: "AD_DOCK_STATUS",
    ppiId: PpiId.AD_DOCK_STATUS,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "No payload",
    lenHint: "len=0",
  },
  RING_STATUS_RQ: {
    title: "Ring Status Request",
    actionName: "RING_STATUS_RQ",
    busyKey: "ppi-ring-status-rq",
    ppiName: "AD_RING_STATUS",
    ppiId: PpiId.AD_RING_STATUS,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "No payload",
    lenHint: "len=0",
  },
  DEVELOPMENT_CMD_RQ: {
    title: "Development Command Request",
    actionName: "DEVELOPMENT_CMD_RQ",
    busyKey: "ppi-development-cmd-rq",
    ppiName: "AD_DEVELOPMENT_CMD",
    ppiId: PpiId.AD_DEVELOPMENT_CMD,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "uint8 dock_command_id",
    lenHint: "len=1",
    payloadPreview: "Uses Dev Cmd input (0-255 decimal or 0x00-0xFF).",
  },
  CALIBRATION_DATA_RQ: {
    title: "Calibration Data Request",
    actionName: "CALIBRATION_DATA_RQ",
    busyKey: "ppi-calibration-data-rq",
    ppiName: "AD_CALIBRATION_DATA",
    ppiId: PpiId.AD_CALIBRATION_DATA,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "No payload",
    lenHint: "len=0",
  },
  START_CALIBRATION_RQ: {
    title: "Start Calibration",
    actionName: "START_CALIBRATION_RQ",
    busyKey: "ppi-start-calibration-rq",
    ppiName: "AD_START_CALIBRATION",
    ppiId: PpiId.AD_START_CALIBRATION,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "start=true + calibration_weight_mg",
    lenHint: "len=5",
    payloadPreview: "Uses Calibration Weight input (mg).",
  },
  STOP_CALIBRATION_RQ: {
    title: "Stop Calibration",
    actionName: "STOP_CALIBRATION_RQ",
    busyKey: "ppi-stop-calibration-rq",
    ppiName: "AD_START_CALIBRATION",
    ppiId: PpiId.AD_START_CALIBRATION,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "start=false + calibration_weight_mg",
    lenHint: "len=5",
    payloadPreview: "Uses Calibration Weight input (mg).",
  },
  CALIBRATION_WEIGHT_PRESENT_PUSH_TRUE: {
    title: "Calibration Weight Present",
    actionName: "CALIBRATION_WEIGHT_PRESENT_PUSH_TRUE",
    busyKey: "ppi-calibration-weight-present-push-true",
    ppiName: "AD_CALIBRATION_WEIGHT_PRESENT",
    ppiId: PpiId.AD_CALIBRATION_WEIGHT_PRESENT,
    typeName: "PUSH",
    typeId: PpiType.PUSH,
    payloadHint: "is_present=true",
    lenHint: "len=1",
    payloadPreview: {
      is_present: true,
    },
  },
  CALIBRATION_WEIGHT_PRESENT_PUSH_FALSE: {
    title: "Calibration Weight Removed",
    actionName: "CALIBRATION_WEIGHT_PRESENT_PUSH_FALSE",
    busyKey: "ppi-calibration-weight-present-push-false",
    ppiName: "AD_CALIBRATION_WEIGHT_PRESENT",
    ppiId: PpiId.AD_CALIBRATION_WEIGHT_PRESENT,
    typeName: "PUSH",
    typeId: PpiType.PUSH,
    payloadHint: "is_present=false",
    lenHint: "len=1",
    payloadPreview: {
      is_present: false,
    },
  },
  START_BASELINING_RQ: {
    title: "Start Baselining",
    actionName: "START_BASELINING_RQ",
    busyKey: "ppi-start-baselining-rq",
    ppiName: "AD_START_BASELINING",
    ppiId: PpiId.AD_START_BASELINING,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "start=true",
    lenHint: "len=1",
    payloadPreview: {
      start: true,
    },
  },
  STOP_BASELINING_RQ: {
    title: "Stop Baselining",
    actionName: "STOP_BASELINING_RQ",
    busyKey: "ppi-stop-baselining-rq",
    ppiName: "AD_START_BASELINING",
    ppiId: PpiId.AD_START_BASELINING,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "start=false",
    lenHint: "len=1",
    payloadPreview: {
      start: false,
    },
  },
  VALIDATE_MED_RE_TRUE: {
    title: "Validate Med Success",
    actionName: "VALIDATE_MED_RE_TRUE",
    busyKey: "ppi-validate-med-re-true",
    ppiName: "AD_VALIDATE_MED",
    ppiId: PpiId.AD_VALIDATE_MED,
    typeName: "RE",
    typeId: PpiType.RE,
    payloadHint: "success=true",
    lenHint: "len=1",
    payloadPreview: {
      success: true,
    },
  },
  VALIDATE_MED_RE_FALSE: {
    title: "Validate Med Failure",
    actionName: "VALIDATE_MED_RE_FALSE",
    busyKey: "ppi-validate-med-re-false",
    ppiName: "AD_VALIDATE_MED",
    ppiId: PpiId.AD_VALIDATE_MED,
    typeName: "RE",
    typeId: PpiType.RE,
    payloadHint: "success=false",
    lenHint: "len=1",
    payloadPreview: {
      success: false,
    },
  },
  DOCK_BATTERY_RQ: {
    title: "Dock Battery Request",
    actionName: "DOCK_BATTERY_RQ",
    busyKey: "ppi-dock-battery-rq",
    ppiName: "AD_DOCK_BATT_LEVEL_LOG",
    ppiId: PpiId.AD_DOCK_BATT_LEVEL_LOG,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "No payload",
    lenHint: `RE/PUSH expected len=${BATTERY_LEVEL_T_SIZE_BYTES}`,
  },
  RING_BATTERY_RQ: {
    title: "Ring Battery Request",
    actionName: "RING_BATTERY_RQ",
    busyKey: "ppi-ring-battery-rq",
    ppiName: "AD_RING_BATT_LEVEL_LOG",
    ppiId: PpiId.AD_RING_BATT_LEVEL_LOG,
    typeName: "RQ",
    typeId: PpiType.RQ,
    payloadHint: "No payload",
    lenHint: `RE/PUSH expected len=${BATTERY_LEVEL_T_SIZE_BYTES}`,
  },
};

export const PPI_TX_READY_POLL_MS = 100;
// Firmware parity:
// - ACK_TIMEOUT_MS = 1000
// - MSG_PROT_MAX_RETRIES = 20
// - MESSAGE_PROTOCOL_PROCESS_INTERVAL_MS = 0
export const PPI_ACK_TIMEOUT_MS = 1000;
export const PPI_MAX_RETRIES = 20;
// In firmware, ABANDONED is reached after the initial wait + retries:
// (maxRetries + 1) * ackTimeout = 21 * 1000 = 21000 ms.
// Keep a small guard band in debug UI waiters.
export const PPI_TX_COMPLETION_WAIT_MS = 23000;
export const PPI_TX_READY_TIMEOUT_MS = 23000;
export const PPI_LATE_ACK_WATCH_TIMEOUT_MS = 23000;
export const PPI_LATE_ACK_WATCH_POLL_MS = 120;
