import { StyleSheet } from "react-native";

import {
  validoseAqua3,
  validoseButtonColor,
  validoseDarkBlue,
  validoseGrey,
  validoseWhite,
} from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: validoseWhite },
  keyboardContainer: { flex: 1 },
  content: { padding: 16, paddingBottom: 48, alignItems: "center", backgroundColor: validoseWhite },
  topInfoWrap: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    gap: 10,
    marginBottom: 8,
  },
  panel: {
    width: "100%",
    maxWidth: 560,
    backgroundColor: validoseWhite,
    borderRadius: 12,
    paddingHorizontal: 0,
    paddingVertical: 0,
    gap: 12,
  },
  header: { flexDirection: "row", alignItems: "center", gap: 10 },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: validoseAqua3,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: validoseWhite,
  },
  backButtonText: { color: validoseAqua3, fontSize: 18, lineHeight: 20, fontWeight: "700" },
  title: { fontSize: 24, fontWeight: "700", color: validoseDarkBlue },
  logsButton: {
    marginLeft: "auto",
    borderWidth: 1,
    borderColor: validoseAqua3,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: validoseWhite,
  },
  logsButtonText: {
    color: validoseAqua3,
    fontSize: 12,
    fontWeight: "700",
  },
  connectionBanner: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 11,
    paddingVertical: 9,
    // gap: 3,
  },
  connectionBannerConnected: {
    borderColor: "#A9E6BF",
    backgroundColor: "#EEFFF3",
  },
  connectionBannerDisconnected: {
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
  },
  connectionBannerTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
    flexShrink: 1,
  },
  connectionBannerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  connectionDot: {
    width: 7,
    height: 7,
    borderRadius: 99,
  },
  connectionDotConnected: {
    backgroundColor: "#12B76A",
  },
  connectionDotDisconnected: {
    backgroundColor: "#98A2B3",
  },
  connectionStatusText: {
    fontSize: 13,
    fontWeight: "700",
  },
  connectionStatusTextConnected: {
    color: "#087443",
  },
  connectionStatusTextDisconnected: {
    color: "#475467",
  },
  connectionDeviceText: {
    fontSize: 11,
    color: validoseDarkBlue,
    fontWeight: "600",
    marginLeft: 14,
    marginTop: 2
    // lineHeight: 15,
  },
  guideCard: {
    borderWidth: 1,
    borderColor: "#D5D9E0",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#F8FAFC",
    gap: 8,
  },
  guideTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  guideTopTextWrap: {
    flex: 1,
  },
  guideTitle: {
    fontSize: 13,
    color: validoseDarkBlue,
    fontWeight: "700",
  },
  guideToggle: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    minWidth: 52,
    alignItems: "center",
  },
  guideToggleActive: {
    borderColor: "#12B76A",
    backgroundColor: "#ECFDF3",
  },
  guideToggleInactive: {
    borderColor: "#D0D5DD",
    backgroundColor: validoseWhite,
  },
  guideToggleText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#667085",
  },
  guideToggleTextActive: {
    color: "#087443",
  },
  guideHint: {
    fontSize: 11,
    color: "#344054",
    lineHeight: 16,
  },
  guideProgressText: {
    fontSize: 11,
    color: "#087443",
    fontWeight: "700",
  },
  statusCard: {
    borderWidth: 1,
    borderColor: "#D6E8EC",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#F4FBFD",
    gap: 8,
  },
  statusTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusLabel: { fontSize: 12, fontWeight: "700", color: validoseDarkBlue },
  statusBusy: { flexDirection: "row", gap: 6, alignItems: "center" },
  statusBusyText: { fontSize: 12, fontWeight: "700", color: validoseButtonColor },
  statusIdle: { fontSize: 12, color: validoseGrey, fontWeight: "700" },
  statusEvent: { fontSize: 12, color: validoseDarkBlue },
  simpleFlowCard: {
    borderWidth: 1,
    borderColor: "#D6E8EC",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#F8FCFD",
    gap: 8,
  },
  simpleStepCards: {
    gap: 8,
  },
  simpleStepCard: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    gap: 8,
    backgroundColor: validoseWhite,
  },
  simpleStepCardDone: {
    borderColor: "#A9E6BF",
    backgroundColor: "#F1FFF6",
  },
  simpleStepCardNext: {
    borderColor: "#B9DCE4",
    backgroundColor: "#F4FBFD",
  },
  simpleStepCardLocked: {
    borderColor: "#E4E7EC",
    backgroundColor: "#FAFBFC",
  },
  simpleStepHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  simpleStepIndex: {
    width: 18,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "800",
    color: validoseButtonColor,
  },
  simpleStepTitleWrap: {
    flex: 1,
    gap: 2,
  },
  simpleStepTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  simpleStepHelp: {
    fontSize: 11,
    color: validoseGrey,
    lineHeight: 15,
  },
  simpleStepBadge: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  simpleStepBadgeDone: {
    borderColor: "#A9E6BF",
    backgroundColor: "#ECFDF3",
  },
  simpleStepBadgeNext: {
    borderColor: "#B9DCE4",
    backgroundColor: "#EAF6F8",
  },
  simpleStepBadgeLocked: {
    borderColor: "#E4E7EC",
    backgroundColor: "#F2F4F7",
  },
  simpleStepBadgeText: {
    fontSize: 10,
    fontWeight: "700",
  },
  simpleStepBadgeTextDone: {
    color: "#087443",
  },
  simpleStepBadgeTextNext: {
    color: validoseButtonColor,
  },
  simpleStepBadgeTextLocked: {
    color: "#667085",
  },
  simpleStepActionWrap: {
    marginTop: 2,
  },
  simpleInlineHint: { fontSize: 11, color: validoseGrey },
  simpleInlineStatus: { fontSize: 11, color: validoseDarkBlue },
  simpleFooterRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  simpleFooterButton: {
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: validoseWhite,
  },
  simpleFooterButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#344054",
  },
  simpleLinkButton: {
    alignSelf: "flex-start",
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  simpleLinkButtonText: {
    fontSize: 11,
    color: validoseButtonColor,
    fontWeight: "700",
  },
  panelTabs: { flexDirection: "row", justifyContent: "space-between", gap: 6 },
  tabButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "#F9FBFC",
  },
  tabButtonActive: {
    borderColor: validoseButtonColor,
    backgroundColor: "#EAF6F8",
  },
  tabText: { fontSize: 12, color: validoseGrey, fontWeight: "700" },
  tabTextActive: { color: validoseButtonColor },
  section: {
    borderWidth: 1,
    borderColor: "#E6E7E8",
    borderRadius: 12,
    padding: 12,
    gap: 8,
    backgroundColor: validoseWhite,
  },
  carouselContainer: {
    gap: 10,
  },
  carouselContent: {
    gap: 12,
    paddingRight: 2,
  },
  carouselCard: {
    flexShrink: 0,
  },
  carouselStackCard: {
    gap: 12,
  },
  carouselDots: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  carouselDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "#C7CDD4",
  },
  carouselDotActive: {
    width: 20,
    backgroundColor: validoseButtonColor,
  },
  protocolInfoCard: {
    borderRadius: 12,
    backgroundColor: "#F8FAFC",
    padding: 12,
    gap: 10,
  },
  protocolInfoTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  protocolInfoGrid: {
    gap: 6,
  },
  protocolInfoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E9EDF2",
    paddingBottom: 6,
  },
  protocolInfoLabel: {
    flex: 1,
    fontSize: 11,
    color: validoseGrey,
    fontWeight: "600",
  },
  protocolInfoValue: {
    flex: 1,
    fontSize: 11,
    color: validoseDarkBlue,
    fontWeight: "700",
    textAlign: "right",
  },
  sectionTitle: { fontSize: 14, fontWeight: "700", color: validoseDarkBlue },
  sectionHint: {
    fontSize: 11,
    color: validoseGrey,
    lineHeight: 16,
  },
  deviceActionButton: {
    borderRadius: 16,
    minHeight: 32,
    minWidth: 102,
    paddingHorizontal: 10,
    paddingVertical: 5,
    alignItems: "center",
    justifyContent: "center",
  },
  advancedWriteCard: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 10,
    backgroundColor: "#FAFBFC",
    padding: 10,
    gap: 8,
  },
  advancedWriteHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  advancedWriteTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  advancedWriteToggle: {
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: validoseWhite,
  },
  advancedWriteToggleText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#344054",
  },
  advancedWriteHint: {
    fontSize: 11,
    color: validoseGrey,
  },
  inputLabel: { fontSize: 12, color: validoseGrey, fontWeight: "600" },
  input: {
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
    backgroundColor: "#FBFCFE",
    color: validoseDarkBlue,
    fontSize: 14,
  },
  writeInput: { minHeight: 76, textAlignVertical: "top" },
  row: { flexDirection: "row", gap: 8, flexWrap: "wrap", alignItems: "center" },
  ppiSection: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#E6E7E8",
    paddingTop: 10,
    gap: 8,
  },
  ppiTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  ppiGroupTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
    marginTop: 4,
  },
  ppiHint: {
    fontSize: 11,
    color: validoseGrey,
  },
  ppiModeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 14,
  },
  ppiModeLabel: {
    fontSize: 12,
    color: validoseDarkBlue,
    fontWeight: "700",
  },
  ppiModeToggle: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  ppiModeToggleActive: {
    borderColor: "#12B76A",
    backgroundColor: "#ECFDF3",
  },
  ppiModeToggleInactive: {
    borderColor: "#D0D8DF",
    backgroundColor: "#F9FBFC",
  },
  ppiModeToggleDisabled: {
    opacity: 0.55,
  },
  ppiModeToggleText: {
    fontSize: 11,
    fontWeight: "700",
    color: validoseGrey,
  },
  ppiModeToggleTextActive: {
    color: "#087443",
  },
  ppiModeToggleTextDisabled: {
    color: "#667085",
  },
  quickPpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  quickPpiCarouselViewport: {
    width: "100%",
  },
  quickPpiCarouselContent: {
    alignItems: "flex-start",
  },
  quickPpiPage: {
    paddingRight: 2,
    paddingBottom: 2,
  },
  quickDevInputCard: {
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 10,
    backgroundColor: "#FAFBFC",
    padding: 10,
    gap: 6,
    marginBottom: 10,
  },
  quickDevInputLabel: {
    fontSize: 11,
    color: validoseDarkBlue,
    fontWeight: "700",
  },
  quickDevInput: {
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 8,
    backgroundColor: validoseWhite,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 13,
    color: validoseDarkBlue,
  },
  quickDevInputError: {
    borderColor: "#F04438",
  },
  quickDevInputHint: {
    fontSize: 10,
    color: "#667085",
    fontWeight: "600",
  },
  quickDevInputErrorText: {
    fontSize: 10,
    color: "#B42318",
    fontWeight: "700",
  },
  quickDevCommandCard: {
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 12,
    backgroundColor: "#F8FAFC",
    padding: 10,
    gap: 8,
    marginBottom: 2,
  },
  quickDevCommandHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  quickDevCommandTitle: {
    fontSize: 12,
    color: validoseDarkBlue,
    fontWeight: "800",
  },
  quickDevCommandMeta: {
    fontSize: 10,
    color: "#667085",
    fontWeight: "700",
  },
  quickDevInlineInputWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 8,
    backgroundColor: validoseWhite,
    minHeight: 40,
  },
  quickDevInlineInputWrapError: {
    borderColor: "#F04438",
  },
  quickDevInlineInputPrefix: {
    fontSize: 11,
    color: "#475467",
    fontWeight: "700",
    paddingLeft: 10,
    paddingRight: 8,
  },
  quickDevInlineInput: {
    flex: 1,
    color: validoseDarkBlue,
    fontSize: 13,
    paddingVertical: 8,
    paddingRight: 10,
  },
  quickPageFeedbackWrap: {
    marginTop: 10,
    gap: 10,
  },
  baseliningGuideCard: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 14,
    backgroundColor: validoseWhite,
    padding: 12,
    gap: 10,
  },
  baseliningGuideHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  baseliningGuideTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#111827",
  },
  baseliningGuideUpdatedAt: {
    fontSize: 10,
    color: "#667085",
    fontWeight: "600",
  },
  baseliningGuideCurrentState: {
    fontSize: 12,
    color: validoseButtonColor,
    fontWeight: "800",
  },
  baseliningGuideStageRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  baseliningGuideStagePill: {
    fontSize: 10,
    fontWeight: "800",
    color: validoseButtonColor,
    borderWidth: 1,
    borderColor: "#B9DCE4",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "#EAF6F8",
    overflow: "hidden",
  },
  baseliningGuideInstruction: {
    fontSize: 10,
    lineHeight: 14,
    color: "#344054",
    fontWeight: "600",
  },
  baseliningGuideMetricsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  baseliningGuideMetricChip: {
    minWidth: "47%",
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: "#F9FAFB",
    gap: 2,
  },
  baseliningGuideMetricLabel: {
    fontSize: 9,
    color: "#667085",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.2,
  },
  baseliningGuideMetricValue: {
    fontSize: 11,
    color: "#1F2937",
    fontWeight: "700",
  },
  baseliningGuideNfcRow: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: "#FBFCFE",
    gap: 3,
  },
  baseliningGuideNfcLabel: {
    fontSize: 9,
    color: "#667085",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.2,
  },
  baseliningGuideNfcValue: {
    fontSize: 10,
    color: "#1F2937",
    fontWeight: "700",
  },
  baseliningGuideStateList: {
    gap: 6,
  },
  baseliningGuideStateItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    backgroundColor: "#FAFBFC",
  },
  baseliningGuideStateItemActive: {
    borderColor: "#B9DCE4",
    backgroundColor: "#EAF6F8",
  },
  baseliningGuideStateItemError: {
    borderColor: "#FECACA",
    backgroundColor: "#FEF2F2",
  },
  baseliningGuideStateCode: {
    minWidth: 16,
    fontSize: 10,
    fontWeight: "800",
    color: "#667085",
    textAlign: "center",
    paddingTop: 1,
  },
  baseliningGuideStateCodeActive: {
    color: validoseButtonColor,
  },
  baseliningGuideStateTextWrap: {
    flex: 1,
    gap: 2,
  },
  baseliningGuideStateLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "#344054",
  },
  baseliningGuideStateLabelActive: {
    color: validoseButtonColor,
  },
  baseliningGuideStateHint: {
    fontSize: 9,
    lineHeight: 12,
    color: "#B42318",
    fontWeight: "600",
  },
  calibrationGuideCard: {
    borderColor: "#E4E7EC",
    borderRadius: 14,
    backgroundColor: validoseWhite,
  },
  calibrationGuideHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  calibrationGuideTitle: {
    fontSize: 13,
    fontWeight: "800",
    color: "#111827",
  },
  calibrationGuideStagePill: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  calibrationGuideStagePillIdle: {
    borderColor: "#D0D5DD",
    backgroundColor: "#F8FAFC",
  },
  calibrationGuideStagePillActive: {
    borderColor: "#B9DCE4",
    backgroundColor: "#EAF6F8",
  },
  calibrationGuideStagePillDone: {
    borderColor: "#ABEFC6",
    backgroundColor: "#ECFDF3",
  },
  calibrationGuideStageText: {
    fontSize: 10,
    fontWeight: "700",
  },
  calibrationGuideStageTextIdle: {
    color: "#667085",
  },
  calibrationGuideStageTextActive: {
    color: validoseButtonColor,
  },
  calibrationGuideStageTextDone: {
    color: "#087443",
  },
  calibrationGuideInstructionText: {
    fontSize: 11,
    lineHeight: 16,
    color: "#344054",
    fontWeight: "600",
  },
  calibrationGuideCompletionText: {
    fontSize: 11,
    lineHeight: 16,
    color: "#087443",
    fontWeight: "700",
  },
  calibrationGuideSignalRow: {
    flexDirection: "row",
    gap: 6,
  },
  calibrationGuideSignalChip: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 7,
    backgroundColor: "#F9FAFB",
    gap: 2,
  },
  calibrationGuideSignalLabel: {
    fontSize: 9,
    color: "#667085",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  calibrationGuideSignalValue: {
    fontSize: 11,
    color: "#1F2937",
    fontWeight: "700",
  },
  calibrationGuideDataCard: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 10,
    padding: 10,
    backgroundColor: "#FBFCFE",
    gap: 8,
    marginTop: 8
  },
  calibrationGuideDataHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 6,
  },
  calibrationGuideDataTitle: {
    fontSize: 11,
    color: "#111827",
    fontWeight: "700",
  },
  calibrationGuideDataUpdatedAt: {
    fontSize: 10,
    color: "#667085",
    fontWeight: "600",
  },
  calibrationGuideDataEmpty: {
    fontSize: 11,
    color: "#98A2B3",
    fontStyle: "italic",
  },
  calibrationGuideDataGrid: {
    flexDirection: "row",
    gap: 6,
  },
  calibrationGuideDataCell: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 8,
    paddingHorizontal: 7,
    paddingVertical: 6,
    backgroundColor: validoseWhite,
    gap: 3,
  },
  calibrationGuideDataLabel: {
    fontSize: 9,
    color: "#667085",
    fontWeight: "700",
  },
  calibrationGuideDataValue: {
    fontSize: 11,
    color: "#101828",
    fontWeight: "800",
  },
  quickPpiPageTitle: {
    fontSize: 11,
    fontWeight: "700",
    color: validoseGrey,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  quickPpiPager: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    marginTop: 10,
  },
  quickPpiPagerDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#D0D8DF",
  },
  quickPpiPagerDotActive: {
    width: 20,
    borderRadius: 999,
    backgroundColor: validoseButtonColor,
  },
  quickPpiButton: {
    flexBasis: "48%",
    maxWidth: "48%",
    borderWidth: 1.5,
    borderColor: "#B9DCE4",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#F4FBFD",
    gap: 6,
  },
  quickPpiButtonDisabled: {
    borderColor: "#D0D5DD",
    backgroundColor: "#F2F4F7",
    opacity: 1,
  },
  quickPpiButtonFullWidth: {
    flexBasis: "auto",
    width: "100%",
    maxWidth: "100%",
    alignSelf: "stretch",
  },
  quickPpiButtonTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  quickPpiButtonActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
  },
  quickPpiLoaderSlot: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  quickPpiInfoButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#B9DCE4",
    backgroundColor: validoseWhite,
  },
  quickPpiInfoButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: validoseButtonColor,
    lineHeight: 13,
  },
  quickPpiInfoButtonDisabled: {
    borderColor: "#D0D5DD",
    backgroundColor: "#EAECF0",
  },
  quickPpiInfoButtonTextDisabled: {
    color: "#98A2B3",
  },
  quickPpiButtonTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: validoseDarkBlue,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  quickPpiButtonTitleDisabled: {
    color: "#98A2B3",
  },
  quickPpiButtonSubtitle: {
    fontSize: 11,
    color: validoseGrey,
  },
  quickPpiButtonSubtitleDisabled: {
    color: "#98A2B3",
  },
  flowGuideCard: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 10,
    backgroundColor: "#FAFBFC",
    padding: 10,
    gap: 8,
  },
  flowGuideHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  flowGuideTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  flowGuideStatus: {
    fontSize: 10,
    fontWeight: "700",
    color: validoseButtonColor,
    borderWidth: 1,
    borderColor: "#B9DCE4",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: "#F4FBFD",
  },
  flowGuideMode: {
    fontSize: 11,
    color: validoseGrey,
    fontWeight: "600",
  },
  flowActionSelector: {
    gap: 8,
    paddingRight: 2,
    paddingBottom: 2,
  },
  flowActionChip: {
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: validoseWhite,
  },
  flowActionChipActive: {
    borderColor: validoseButtonColor,
    backgroundColor: validoseButtonColor,
  },
  flowActionChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#344054",
  },
  flowActionChipTextActive: {
    color: validoseWhite,
  },
  flowStepsList: {
    gap: 8,
  },
  flowStepRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  flowStepRail: {
    width: 12,
    alignItems: "center",
  },
  flowStepDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "#C7CDD4",
    marginTop: 6,
  },
  flowStepConnector: {
    width: 1,
    flex: 1,
    marginTop: 4,
    borderRadius: 99,
    backgroundColor: "#D0D5DD",
  },
  flowStepConnectorDone: {
    backgroundColor: "#12B76A",
  },
  flowStepConnectorError: {
    backgroundColor: "#D92D20",
  },
  flowStepCard: {
    flex: 1,
    borderWidth: 0,
    borderRadius: 8,
    backgroundColor: "transparent",
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 2,
  },
  flowStepCardActive: {
    backgroundColor: "#EAF6F8",
  },
  flowStepCardDone: {
    backgroundColor: "#ECFDF3",
  },
  flowStepCardError: {
    backgroundColor: "#FEF3F2",
  },
  flowStepNumber: {
    fontSize: 10,
    fontWeight: "800",
    color: validoseButtonColor,
  },
  flowStepDotActive: {
    backgroundColor: validoseButtonColor,
  },
  flowStepDotDone: {
    backgroundColor: "#12B76A",
  },
  flowStepDotError: {
    backgroundColor: "#D92D20",
  },
  flowStepText: {
    fontSize: 11,
    lineHeight: 17,
    color: validoseGrey,
  },
  flowStepTextActive: {
    color: validoseDarkBlue,
    fontWeight: "700",
  },
  flowStepTextDone: {
    color: "#087443",
    fontWeight: "600",
  },
  flowStepTextError: {
    color: "#B42318",
    fontWeight: "700",
  },
  flowModalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15,23,42,0.4)",
  },
  flowModalDismissArea: {
    flex: 1,
  },
  flowModalCard: {
    maxHeight: "78%",
    backgroundColor: validoseWhite,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderTopWidth: 1,
    borderColor: "#E7EBF0",
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 20,
    gap: 10,
  },
  flowModalHandle: {
    alignSelf: "center",
    width: 38,
    height: 4,
    borderRadius: 99,
    backgroundColor: "#D0D5DD",
    marginBottom: 2,
  },
  flowModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    marginBottom: 2,
  },
  flowModalHeaderTextWrap: {
    flex: 1,
    gap: 2,
  },
  flowModalTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  flowModalClose: {
    borderWidth: 1,
    borderColor: validoseButtonColor,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: validoseButtonColor,
  },
  flowModalCloseText: {
    fontSize: 11,
    fontWeight: "700",
    color: validoseWhite,
  },
  flowModalSubtitle: {
    fontSize: 11,
    color: "#667085",
    fontWeight: "600",
  },
  flowModalMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  flowModalMetaPill: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: "#F8FAFC",
  },
  flowModalMetaPillStatus: {
    borderColor: "#B9DCE4",
    backgroundColor: "#EAF6F8",
  },
  flowModalMetaText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#344054",
  },
  flowModalMetaTextStatus: {
    fontSize: 10,
    fontWeight: "800",
    color: validoseButtonColor,
  },
  flowModalCurrentCard: {
    borderWidth: 1,
    borderColor: "#DCECF0",
    borderRadius: 10,
    backgroundColor: "#F7FBFD",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  flowModalCurrentLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: validoseGrey,
  },
  flowModalCurrentText: {
    fontSize: 11,
    lineHeight: 16,
    color: validoseDarkBlue,
    fontWeight: "600",
  },
  flowModalStepsScroll: {
    maxHeight: 430,
  },
  compactFeedbackCard: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 14,
    backgroundColor: validoseWhite,
    padding: 10,
    gap: 8,
    shadowColor: "#101828",
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  compactFeedbackHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  compactFeedbackTitleWrap: {
    flex: 1,
    gap: 1,
  },
  compactFeedbackTitle: {
    fontSize: 12,
    fontWeight: "800",
    color: "#111827",
  },
  compactFeedbackSubtitle: {
    fontSize: 9,
    color: "#667085",
    fontWeight: "600",
  },
  compactFeedbackLivePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: "#D5EBDD",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 3,
    backgroundColor: "#F4FBF7",
  },
  compactFeedbackLiveDot: {
    width: 6,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#12B76A",
  },
  compactFeedbackLiveText: {
    fontSize: 9,
    color: "#0F5132",
    fontWeight: "700",
  },
  compactFeedbackLegendRow: {
    flexDirection: "row",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 6,
  },
  compactFeedbackCodeHint: {
    fontSize: 10,
    color: "#667085",
    fontWeight: "600",
  },
  compactFeedbackLegendChip: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: "#F9FAFB",
  },
  compactFeedbackLegendChipText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#344054",
  },
  compactFeedbackLaneGrid: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 6,
  },
  compactFeedbackSlot: {
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 7,
    gap: 4,
    backgroundColor: "#FBFCFE",
    minHeight: 58,
  },
  compactFeedbackSlotResponse: {
    borderColor: "#D4E3F5",
  },
  compactFeedbackSlotFeedback: {
    borderColor: "#D3ECDD",
  },
  compactFeedbackSlotTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  compactFeedbackBadge: {
    fontSize: 9,
    fontWeight: "700",
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 6,
    paddingVertical: 1,
    overflow: "hidden",
  },
  compactFeedbackBadgeResponse: {
    color: "#204E7A",
    borderColor: "#D4E3F5",
    backgroundColor: "#F3F8FE",
  },
  compactFeedbackBadgeFeedback: {
    color: "#1B6A49",
    borderColor: "#D3ECDD",
    backgroundColor: "#F2FBF6",
  },
  compactFeedbackTime: {
    fontSize: 9,
    color: "#667085",
    fontWeight: "600",
  },
  compactFeedbackTokenRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 5,
  },
  compactFeedbackToken: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 999,
    paddingHorizontal: 7,
    paddingVertical: 2,
    backgroundColor: "#F9FAFB",
  },
  compactFeedbackTokenText: {
    fontSize: 9,
    fontWeight: "700",
    color: "#344054",
  },
  compactFeedbackMeta: {
    fontSize: 10,
    color: "#667085",
    fontWeight: "600",
  },
  compactFeedbackText: {
    fontSize: 10,
    lineHeight: 14,
    color: validoseDarkBlue,
    fontWeight: "600",
  },
  compactFeedbackEmpty: {
    fontSize: 10,
    color: "#98A2B3",
    fontStyle: "italic",
  },
  ppiPreviewCard: {
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 10,
    backgroundColor: "#FAFBFC",
    padding: 10,
    gap: 6,
  },
  ppiPreviewTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  ppiPreviewPrimaryLabel: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: "800",
    color: "#0B5F71",
  },
  lastPacketActionRow: {
    flexDirection: "row",
  },
  lastPacketActionButton: {
    flex: 1,
    borderRadius: 10,
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  ppiPreviewMeta: {
    fontSize: 11,
    color: validoseGrey,
    fontWeight: "600",
  },
  ppiPreviewLine: {
    fontSize: 11,
    color: validoseDarkBlue,
  },
  ppiPreviewSectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: validoseDarkBlue,
    marginTop: 2,
  },
  ppiPreviewToggle: {
    marginTop: 2,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: validoseWhite,
  },
  ppiPreviewToggleText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#344054",
  },
  ppiPreviewCode: {
    fontSize: 11,
    lineHeight: 16,
    color: validoseDarkBlue,
    fontFamily: "Courier",
  },
  ppiPreviewEmpty: {
    fontSize: 11,
    color: validoseGrey,
  },
  actionButton: {
    borderWidth: 2,
    borderColor: validoseButtonColor,
    borderRadius: 25,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: validoseButtonColor,
  },
  actionButtonDanger: {
    borderColor: "#B42318",
    backgroundColor: "#B42318",
  },
  actionButtonDisabled: {
    borderColor: "#D0D5DD",
    backgroundColor: "#EAECF0",
    opacity: 1,
  },
  actionButtonInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  actionButtonText: { color: validoseWhite, fontSize: 12, fontWeight: "700" },
  actionButtonTextDanger: { color: validoseWhite },
  actionButtonTextDisabled: { color: "#98A2B3" },
  modeRow: { flexDirection: "row", gap: 8, justifyContent: "center" },
  modeButton: {
    borderWidth: 1.5,
    borderColor: validoseAqua3,
    borderRadius: 25,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: validoseWhite,
  },
  modeButtonActive: {
    backgroundColor: validoseButtonColor,
    borderColor: validoseButtonColor,
  },
  modeText: { color: validoseAqua3, fontWeight: "700", fontSize: 11 },
  modeTextActive: { color: validoseWhite },
});
