import { StyleSheet } from "react-native";

import {
  validoseAqua3,
  validoseButtonColor,
  validoseDarkBlue,
  validoseGrey,
  validoseWhite,
} from "@/constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: validoseWhite },
  keyboardContainer: { flex: 1 },
  content: { padding: 16, paddingBottom: 48, alignItems: "center", backgroundColor: validoseWhite },
  topInfoWrap: {
    width: "100%",
    maxWidth: 560,
    alignSelf: "center",
    gap: 10,
    marginBottom: 8,
  },
  panel: {
    width: "100%",
    maxWidth: 560,
    backgroundColor: validoseWhite,
    borderRadius: 12,
    paddingHorizontal: 0,
    paddingVertical: 0,
    gap: 12,
  },
  header: { flexDirection: "row", alignItems: "center", gap: 10 },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: validoseAqua3,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: validoseWhite,
  },
  backButtonText: { color: validoseAqua3, fontSize: 18, lineHeight: 20, fontWeight: "700" },
  title: { fontSize: 24, fontWeight: "700", color: validoseDarkBlue },
  logsButton: {
    marginLeft: "auto",
    borderWidth: 1,
    borderColor: validoseAqua3,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: validoseWhite,
  },
  logsButtonText: {
    color: validoseAqua3,
    fontSize: 12,
    fontWeight: "700",
  },
  connectionBanner: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 4,
  },
  connectionBannerConnected: {
    borderColor: "#A9E6BF",
    backgroundColor: "#EEFFF3",
  },
  connectionBannerDisconnected: {
    borderColor: "#E5E7EB",
    backgroundColor: "#F8FAFC",
  },
  connectionBannerTop: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  connectionDot: {
    width: 8,
    height: 8,
    borderRadius: 99,
  },
  connectionDotConnected: {
    backgroundColor: "#12B76A",
  },
  connectionDotDisconnected: {
    backgroundColor: "#98A2B3",
  },
  connectionStatusText: {
    fontSize: 13,
    fontWeight: "700",
  },
  connectionStatusTextConnected: {
    color: "#087443",
  },
  connectionStatusTextDisconnected: {
    color: "#475467",
  },
  connectionDeviceText: {
    fontSize: 12,
    color: validoseDarkBlue,
    fontWeight: "600",
  },
  guideCard: {
    borderWidth: 1,
    borderColor: "#D5D9E0",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#F8FAFC",
    gap: 8,
  },
  guideTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 10,
  },
  guideTopTextWrap: {
    flex: 1,
  },
  guideTitle: {
    fontSize: 13,
    color: validoseDarkBlue,
    fontWeight: "700",
  },
  guideToggle: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    minWidth: 52,
    alignItems: "center",
  },
  guideToggleActive: {
    borderColor: "#12B76A",
    backgroundColor: "#ECFDF3",
  },
  guideToggleInactive: {
    borderColor: "#D0D5DD",
    backgroundColor: validoseWhite,
  },
  guideToggleText: {
    fontSize: 11,
    fontWeight: "800",
    color: "#667085",
  },
  guideToggleTextActive: {
    color: "#087443",
  },
  guideHint: {
    fontSize: 11,
    color: "#344054",
    lineHeight: 16,
  },
  guideProgressText: {
    fontSize: 11,
    color: "#087443",
    fontWeight: "700",
  },
  statusCard: {
    borderWidth: 1,
    borderColor: "#D6E8EC",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#F4FBFD",
    gap: 8,
  },
  statusTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  statusLabel: { fontSize: 12, fontWeight: "700", color: validoseDarkBlue },
  statusBusy: { flexDirection: "row", gap: 6, alignItems: "center" },
  statusBusyText: { fontSize: 12, fontWeight: "700", color: validoseButtonColor },
  statusIdle: { fontSize: 12, color: validoseGrey, fontWeight: "700" },
  statusEvent: { fontSize: 12, color: validoseDarkBlue },
  simpleFlowCard: {
    borderWidth: 1,
    borderColor: "#D6E8EC",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#F8FCFD",
    gap: 8,
  },
  simpleStepCards: {
    gap: 8,
  },
  simpleStepCard: {
    borderWidth: 1,
    borderRadius: 10,
    padding: 10,
    gap: 8,
    backgroundColor: validoseWhite,
  },
  simpleStepCardDone: {
    borderColor: "#A9E6BF",
    backgroundColor: "#F1FFF6",
  },
  simpleStepCardNext: {
    borderColor: "#B9DCE4",
    backgroundColor: "#F4FBFD",
  },
  simpleStepCardLocked: {
    borderColor: "#E4E7EC",
    backgroundColor: "#FAFBFC",
  },
  simpleStepHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 8,
  },
  simpleStepIndex: {
    width: 18,
    textAlign: "center",
    fontSize: 12,
    fontWeight: "800",
    color: validoseButtonColor,
  },
  simpleStepTitleWrap: {
    flex: 1,
    gap: 2,
  },
  simpleStepTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  simpleStepHelp: {
    fontSize: 11,
    color: validoseGrey,
    lineHeight: 15,
  },
  simpleStepBadge: {
    borderWidth: 1,
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  simpleStepBadgeDone: {
    borderColor: "#A9E6BF",
    backgroundColor: "#ECFDF3",
  },
  simpleStepBadgeNext: {
    borderColor: "#B9DCE4",
    backgroundColor: "#EAF6F8",
  },
  simpleStepBadgeLocked: {
    borderColor: "#E4E7EC",
    backgroundColor: "#F2F4F7",
  },
  simpleStepBadgeText: {
    fontSize: 10,
    fontWeight: "700",
  },
  simpleStepBadgeTextDone: {
    color: "#087443",
  },
  simpleStepBadgeTextNext: {
    color: validoseButtonColor,
  },
  simpleStepBadgeTextLocked: {
    color: "#667085",
  },
  simpleStepActionWrap: {
    marginTop: 2,
  },
  simpleInlineHint: { fontSize: 11, color: validoseGrey },
  simpleInlineStatus: { fontSize: 11, color: validoseDarkBlue },
  simpleFooterRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
  },
  simpleFooterButton: {
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: validoseWhite,
  },
  simpleFooterButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#344054",
  },
  simpleLinkButton: {
    alignSelf: "flex-start",
    paddingVertical: 4,
    paddingHorizontal: 2,
  },
  simpleLinkButtonText: {
    fontSize: 11,
    color: validoseButtonColor,
    fontWeight: "700",
  },
  panelTabs: { flexDirection: "row", justifyContent: "space-between", gap: 6 },
  tabButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: "center",
    backgroundColor: "#F9FBFC",
  },
  tabButtonActive: {
    borderColor: validoseButtonColor,
    backgroundColor: "#EAF6F8",
  },
  tabText: { fontSize: 12, color: validoseGrey, fontWeight: "700" },
  tabTextActive: { color: validoseButtonColor },
  section: {
    borderWidth: 1,
    borderColor: "#E6E7E8",
    borderRadius: 12,
    padding: 12,
    gap: 8,
    backgroundColor: validoseWhite,
  },
  carouselContainer: {
    gap: 10,
  },
  carouselContent: {
    gap: 12,
    paddingRight: 2,
  },
  carouselCard: {
    flexShrink: 0,
  },
  carouselStackCard: {
    gap: 12,
  },
  carouselDots: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
  },
  carouselDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "#C7CDD4",
  },
  carouselDotActive: {
    width: 20,
    backgroundColor: validoseButtonColor,
  },
  protocolInfoCard: {
    borderRadius: 12,
    backgroundColor: "#F8FAFC",
    padding: 12,
    gap: 10,
  },
  protocolInfoTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  protocolInfoGrid: {
    gap: 6,
  },
  protocolInfoRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#E9EDF2",
    paddingBottom: 6,
  },
  protocolInfoLabel: {
    flex: 1,
    fontSize: 11,
    color: validoseGrey,
    fontWeight: "600",
  },
  protocolInfoValue: {
    flex: 1,
    fontSize: 11,
    color: validoseDarkBlue,
    fontWeight: "700",
    textAlign: "right",
  },
  sectionTitle: { fontSize: 14, fontWeight: "700", color: validoseDarkBlue },
  sectionHint: {
    fontSize: 11,
    color: validoseGrey,
    lineHeight: 16,
  },
  deviceActionRow: {
    flexDirection: "row",
    gap: 10,
  },
  deviceActionButton: {
    flex: 1,
    borderRadius: 12,
    minHeight: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  advancedWriteCard: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 10,
    backgroundColor: "#FAFBFC",
    padding: 10,
    gap: 8,
  },
  advancedWriteHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  advancedWriteTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  advancedWriteToggle: {
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: validoseWhite,
  },
  advancedWriteToggleText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#344054",
  },
  advancedWriteHint: {
    fontSize: 11,
    color: validoseGrey,
  },
  inputLabel: { fontSize: 12, color: validoseGrey, fontWeight: "600" },
  input: {
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    minHeight: 44,
    backgroundColor: "#FBFCFE",
    color: validoseDarkBlue,
    fontSize: 14,
  },
  writeInput: { minHeight: 76, textAlignVertical: "top" },
  row: { flexDirection: "row", gap: 8, flexWrap: "wrap", alignItems: "center" },
  ppiSection: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: "#E6E7E8",
    paddingTop: 10,
    gap: 8,
  },
  ppiTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  ppiGroupTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
    marginTop: 4,
  },
  ppiHint: {
    fontSize: 11,
    color: validoseGrey,
  },
  ppiModeRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
    marginTop: 14,
  },
  ppiModeLabel: {
    fontSize: 12,
    color: validoseDarkBlue,
    fontWeight: "700",
  },
  ppiModeToggle: {
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  ppiModeToggleActive: {
    borderColor: "#12B76A",
    backgroundColor: "#ECFDF3",
  },
  ppiModeToggleInactive: {
    borderColor: "#D0D8DF",
    backgroundColor: "#F9FBFC",
  },
  ppiModeToggleDisabled: {
    opacity: 0.55,
  },
  ppiModeToggleText: {
    fontSize: 11,
    fontWeight: "700",
    color: validoseGrey,
  },
  ppiModeToggleTextActive: {
    color: "#087443",
  },
  ppiModeToggleTextDisabled: {
    color: "#667085",
  },
  quickPpiGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  quickPpiButton: {
    flexBasis: "48%",
    maxWidth: "48%",
    borderWidth: 1.5,
    borderColor: "#B9DCE4",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#F4FBFD",
    gap: 6,
  },
  quickPpiButtonDisabled: {
    opacity: 0.65,
  },
  quickPpiButtonTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  quickPpiButtonActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
  },
  quickPpiLoaderSlot: {
    width: 16,
    height: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  quickPpiInfoButton: {
    width: 18,
    height: 18,
    borderRadius: 9,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "#B9DCE4",
    backgroundColor: validoseWhite,
  },
  quickPpiInfoButtonText: {
    fontSize: 11,
    fontWeight: "700",
    color: validoseButtonColor,
    lineHeight: 13,
  },
  quickPpiButtonTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: validoseDarkBlue,
    flex: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  quickPpiButtonSubtitle: {
    fontSize: 11,
    color: validoseGrey,
  },
  flowGuideCard: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 10,
    backgroundColor: "#FAFBFC",
    padding: 10,
    gap: 8,
  },
  flowGuideHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
  },
  flowGuideTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  flowGuideStatus: {
    fontSize: 10,
    fontWeight: "700",
    color: validoseButtonColor,
    borderWidth: 1,
    borderColor: "#B9DCE4",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 2,
    backgroundColor: "#F4FBFD",
  },
  flowGuideMode: {
    fontSize: 11,
    color: validoseGrey,
    fontWeight: "600",
  },
  flowActionSelector: {
    gap: 8,
    paddingRight: 2,
    paddingBottom: 2,
  },
  flowActionChip: {
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 999,
    paddingHorizontal: 11,
    paddingVertical: 7,
    backgroundColor: validoseWhite,
  },
  flowActionChipActive: {
    borderColor: validoseButtonColor,
    backgroundColor: validoseButtonColor,
  },
  flowActionChipText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#344054",
  },
  flowActionChipTextActive: {
    color: validoseWhite,
  },
  flowStepsList: {
    gap: 8,
  },
  flowStepRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  flowStepRail: {
    width: 12,
    alignItems: "center",
  },
  flowStepDot: {
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: "#C7CDD4",
    marginTop: 6,
  },
  flowStepConnector: {
    width: 1,
    flex: 1,
    marginTop: 4,
    borderRadius: 99,
    backgroundColor: "#D0D5DD",
  },
  flowStepConnectorDone: {
    backgroundColor: "#12B76A",
  },
  flowStepConnectorError: {
    backgroundColor: "#D92D20",
  },
  flowStepCard: {
    flex: 1,
    borderWidth: 0,
    borderRadius: 8,
    backgroundColor: "transparent",
    paddingHorizontal: 8,
    paddingVertical: 6,
    gap: 2,
  },
  flowStepCardActive: {
    backgroundColor: "#EAF6F8",
  },
  flowStepCardDone: {
    backgroundColor: "#ECFDF3",
  },
  flowStepCardError: {
    backgroundColor: "#FEF3F2",
  },
  flowStepNumber: {
    fontSize: 10,
    fontWeight: "800",
    color: validoseButtonColor,
  },
  flowStepDotActive: {
    backgroundColor: validoseButtonColor,
  },
  flowStepDotDone: {
    backgroundColor: "#12B76A",
  },
  flowStepDotError: {
    backgroundColor: "#D92D20",
  },
  flowStepText: {
    fontSize: 11,
    lineHeight: 17,
    color: validoseGrey,
  },
  flowStepTextActive: {
    color: validoseDarkBlue,
    fontWeight: "700",
  },
  flowStepTextDone: {
    color: "#087443",
    fontWeight: "600",
  },
  flowStepTextError: {
    color: "#B42318",
    fontWeight: "700",
  },
  flowModalBackdrop: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(15,23,42,0.4)",
  },
  flowModalDismissArea: {
    flex: 1,
  },
  flowModalCard: {
    maxHeight: "78%",
    backgroundColor: validoseWhite,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    borderTopWidth: 1,
    borderColor: "#E7EBF0",
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 20,
    gap: 10,
  },
  flowModalHandle: {
    alignSelf: "center",
    width: 38,
    height: 4,
    borderRadius: 99,
    backgroundColor: "#D0D5DD",
    marginBottom: 2,
  },
  flowModalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    marginBottom: 2,
  },
  flowModalHeaderTextWrap: {
    flex: 1,
    gap: 2,
  },
  flowModalTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  flowModalClose: {
    borderWidth: 1,
    borderColor: validoseButtonColor,
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: validoseButtonColor,
  },
  flowModalCloseText: {
    fontSize: 11,
    fontWeight: "700",
    color: validoseWhite,
  },
  flowModalSubtitle: {
    fontSize: 11,
    color: "#667085",
    fontWeight: "600",
  },
  flowModalMetaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  flowModalMetaPill: {
    borderWidth: 1,
    borderColor: "#E4E7EC",
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
    backgroundColor: "#F8FAFC",
  },
  flowModalMetaPillStatus: {
    borderColor: "#B9DCE4",
    backgroundColor: "#EAF6F8",
  },
  flowModalMetaText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#344054",
  },
  flowModalMetaTextStatus: {
    fontSize: 10,
    fontWeight: "800",
    color: validoseButtonColor,
  },
  flowModalCurrentCard: {
    borderWidth: 1,
    borderColor: "#DCECF0",
    borderRadius: 10,
    backgroundColor: "#F7FBFD",
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  flowModalCurrentLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: validoseGrey,
  },
  flowModalCurrentText: {
    fontSize: 11,
    lineHeight: 16,
    color: validoseDarkBlue,
    fontWeight: "600",
  },
  flowModalStepsScroll: {
    maxHeight: 430,
  },
  ppiPreviewCard: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: "#D2D8DF",
    borderRadius: 10,
    backgroundColor: "#FAFBFC",
    padding: 10,
    gap: 6,
  },
  ppiPreviewTitle: {
    fontSize: 12,
    fontWeight: "700",
    color: validoseDarkBlue,
  },
  ppiPreviewPrimaryLabel: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: "800",
    color: "#0B5F71",
  },
  ppiPreviewMeta: {
    fontSize: 11,
    color: validoseGrey,
    fontWeight: "600",
  },
  ppiPreviewLine: {
    fontSize: 11,
    color: validoseDarkBlue,
  },
  ppiPreviewSectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: validoseDarkBlue,
    marginTop: 2,
  },
  ppiPreviewToggle: {
    marginTop: 2,
    alignSelf: "flex-start",
    borderWidth: 1,
    borderColor: "#D0D8DF",
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: validoseWhite,
  },
  ppiPreviewToggleText: {
    fontSize: 11,
    fontWeight: "700",
    color: "#344054",
  },
  ppiPreviewCode: {
    fontSize: 11,
    lineHeight: 16,
    color: validoseDarkBlue,
    fontFamily: "Courier",
  },
  ppiPreviewEmpty: {
    fontSize: 11,
    color: validoseGrey,
  },
  actionButton: {
    borderWidth: 2,
    borderColor: validoseButtonColor,
    borderRadius: 25,
    paddingHorizontal: 14,
    paddingVertical: 9,
    backgroundColor: validoseButtonColor,
  },
  actionButtonDanger: {
    borderColor: "#B42318",
    backgroundColor: "#B42318",
  },
  actionButtonDisabled: { opacity: 0.65 },
  actionButtonInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },
  actionButtonText: { color: validoseWhite, fontSize: 12, fontWeight: "700" },
  actionButtonTextDanger: { color: validoseWhite },
  modeRow: { flexDirection: "row", gap: 8, justifyContent: "center" },
  modeButton: {
    borderWidth: 1.5,
    borderColor: validoseAqua3,
    borderRadius: 25,
    paddingHorizontal: 14,
    paddingVertical: 8,
    backgroundColor: validoseWhite,
  },
  modeButtonActive: {
    backgroundColor: validoseButtonColor,
    borderColor: validoseButtonColor,
  },
  modeText: { color: validoseAqua3, fontWeight: "700", fontSize: 11 },
  modeTextActive: { color: validoseWhite },
});
