// UUID constants for BLE services and characteristics
export const SERVICE_UUIDS = {
  BATTERY_SERVICE: "180f",
  CUSTOM_SERVICE: "00001500-eb00-430a-a8ff-c7ad4211bf86",
};

export const CHARACTERISTIC_UUIDS = {
  BATTERY_LEVEL: "2a19",
  DOSE_EVENT: "00001504-eb00-430a-a8ff-c7ad4211bf86",
  ERROR_CODE: "00001503-eb00-430a-a8ff-c7ad4211bf86",
  DOSE_SCHEDULE: "00001502-eb00-430a-a8ff-c7ad4211bf86",
  TIME: "00001501-eb00-430a-a8ff-c7ad4211bf86",
  RESET: "00001506-eb00-430a-a8ff-c7ad4211bf86",
};

// Firmware Unit IDs
export enum UnitId {
  INVALID = 0,
  DEBUG,
  QUEUE,
  UART_DRV,
  TWI_DRV,
  SYSTEM_TIME,
  IMU_DRV,
  MAIN_DOCK,
  GENERAL_CONTROL_DOCK,
  BLE_CONTROL_DOCK,
  BATTERY_MANAGER_DOCK,
  LED_CONTROL_DOCK,
  BUZZER_DOCK,
  BLE_CS_DOCK,
  BLE_CS,
  BLE_CONTROL,
  BMS_NPM1300_DRV,
  NOTIFICATIONS_MODULE,
  MAIN_RING,
  GENERAL_CONTROL_RING,
  PROX_SENSOR_TMD2635_DRV,
  CAP_DETECTION_MODULE,
  BMS_BQ25150_DRV,
  MAX,
  UNKNOWN = 0xff,
}

// Mapping error codes per unit
export const UnitErrorCodes: Record<UnitId, Record<number, string>> = {
  [UnitId.INVALID]: {},
  
  [UnitId.DEBUG]: {
    0: "No error",
    1: "TX Mutex error",
    2: "Null pointer error",
    3: "Buffer overflow",
    4: "Failed to get debug level",
    5: "Failed to set debug level",
    6: "Failed to register handler",
  },

  [UnitId.QUEUE]: {
    0: "No error",
    1: "General initialization error",
    2: "Storage size initialization error",
    3: "Queue busy",
    4: "Advance pointer null",
    5: "Enqueue null",
    6: "Enqueue full",
    7: "Dequeue null",
    8: "Dequeue empty",
    9: "Get count null",
    10: "Get available space null",
    11: "Pointer null error",
  },

  [UnitId.UART_DRV]: {
    0: "No error",
    1: "Null pointer error",
    2: "Initialization failed",
    3: "Hardware init null",
    4: "Hardware init failed",
    5: "Transmit null",
    6: "Transmit overflow",
    7: "Processing error",
  },

  [UnitId.TWI_DRV]: {
    0: "No error",
    1: "Null pointer error",
    2: "Timeout",
    3: "General init failure",
    4: "Initialization error",
    5: "Busy",
    6: "Receive error",
    7: "Transmit error",
    8: "Transfer not done",
    9: "Uninitialized",
  },

  [UnitId.SYSTEM_TIME]: {
    0: "No error",
    1: "Null pointer error",
    2: "Overflow error",
  },

  [UnitId.IMU_DRV]: {
    0: "No error",
    1: "Null pointer error",
    2: "Initialization failure",
    3: "I2C error",
    4: "Invalid argument",
    5: "Invalid state",
    6: "No entries",
  },

  [UnitId.MAIN_DOCK]: {},

  [UnitId.GENERAL_CONTROL_DOCK]: {},

  [UnitId.BLE_CONTROL_DOCK]: {},

  [UnitId.BATTERY_MANAGER_DOCK]: {},

  [UnitId.LED_CONTROL_DOCK]: {
    0: "No error",
    1: "Null pointer error",
    2: "Init failure",
    3: "Nordic SDK error",
    4: "I2C write failure",
    5: "Invalid parameter",
    6: "Invalid register address",
    7: "Device not found",
    8: "Timeout",
    9: "Data overflow",
    10: "Device busy",
    11: "Uninitialized",
    12: "Timers init failure",
    13: "Timers start failure",
    14: "Color type set failure",
    15: "Gamma table generation failure",
    16: "Unknown error",
  },

  [UnitId.BUZZER_DOCK]: {
    0: "No error",
    1: "Null pointer error",
    2: "Timer error",
    3: "Frequency error",
  },

  [UnitId.BLE_CS_DOCK]: {},

  [UnitId.BLE_CS]: {},

  [UnitId.BLE_CONTROL]: {
    0: "No error",
    1: "Null pointer error",
    2: "Nordic SDK error",
    3: "Internal error",
    4: "Security params reply error",
    5: "Whitelist population failure",
    6: "Bonding data load failure",
    7: "Peer manager event handler error",
    8: "Peer manager unexpected event error",
    9: "Peer delete failed",
    10: "Peer data update failed",
    11: "Connection error handler error",
    12: "Connection params event error",
    13: "Advertising event error",
    14: "Disconnect error",
    15: "Secure connection failure",
    16: "Queued write request connection handle assign error",
    17: "GAP PHY update error",
    18: "Peer ID list error",
    19: "Device ID list set error",
    20: "Peers delete error",
    21: "Advertising start error",
    22: "Passkey set failure",
    23: "Invalid input error",
  },

  [UnitId.BMS_NPM1300_DRV]: {
    0: "No error",
    1: "Null pointer error",
    2: "Initialization error",
    3: "I2C failure",
    4: "Buffer overflow",
    5: "Invalid address",
    6: "Invalid PMIC switch",
    7: "Invalid command",
    8: "NTC sensor error",
    9: "VBAT sensor error",
    10: "VBAT low error",
    11: "Vtrickle error",
    12: "Measurement timeout",
    13: "Charge timeout",
    14: "Trickle timeout",
    15: "NTC cold sensor value error",
    16: "NTC cool sensor value error",
    17: "NTC warm sensor value error",
    18: "NTC hot sensor value error",
    19: "Vterm sensor value error",
    20: "Recharge sensor value error",
    21: "Vtrickle sensor value error",
    22: "VbatLow sensor value error",
    23: "Shipmode exit reset cause",
    24: "Boot monitor timeout reset cause",
    25: "Watchdog timeout reset cause",
    26: "Long press timeout reset cause",
    27: "Thermal shutdown reset cause",
    28: "VSYS low reset cause",
    29: "Software reset reset cause",
  },

  [UnitId.NOTIFICATIONS_MODULE]: {
    0: "No error",
    1: "Null pointer error",
    2: "Uninitialized module",
    3: "Set LED or buzzer config failure",
    4: "Priority queue error (full)",
    5: "Priority queue empty",
    6: "Color type set failure",
    7: "Timers start failure",
    8: "LED driver init failure",
    9: "Buzzer driver init failure",
  },

  [UnitId.MAIN_RING]: {},

  [UnitId.GENERAL_CONTROL_RING]: {
    0: "No error",
    1: "Null pointer error",
    2: "Overflow",
    3: "Nordic SDK error",
    4: "Nordic SDK error DFU",
    5: "FDS error",
    6: "BLE heartbeat failed",
    7: "BLE heartbeat timeout",
    8: "Invalid stim param received",
    9: "Power management init error",
    10: "Application timer init error",
    11: "Battery too low to start stim",
    12: "Charger connected error",
    13: "Systick init error",
    14: "Flash storage init error",
    15: "Crypto init error",
    16: "Memory init error",
    17: "Passkey decrypt error",
    18: "DFU timer init error",
    19: "PMIC reset timer init error",
    20: "Systick error",
  },

  [UnitId.PROX_SENSOR_TMD2635_DRV]: {
    0: "No error",
    1: "Null pointer error",
    2: "Init failure",
    3: "Nordic SDK error",
    4: "I2C write failure",
    5: "I2C read failure",
    6: "Device not found",
    7: "Uninitialized driver",
    8: "General proximity saturation",
    9: "Reflective saturation",
    10: "Ambient saturation",
    11: "Registers update failure",
  },

  [UnitId.CAP_DETECTION_MODULE]: {
    0: "No error",
    1: "Null pointer error",
    2: "Init failure",
    3: "Nordic SDK error",
    4: "Get status failure",
    5: "Get proximity failure",
    6: "Driver registers update failure",
    7: "Invalid parameter",
    8: "Uninitialized driver",
    9: "Failed to activate driver",
    10: "Unknown error",
  },

  [UnitId.BMS_BQ25150_DRV]: {
    0: "No error",
    1: "Null pointer error",
    2: "Init failure",
    3: "I2C failure",
    4: "Buffer overflow",
    5: "Invalid address",
    6: "Invalid PMIC switch",
    7: "Invalid command",
    8: "VIN OVP",
    9: "BAT OCP",
    10: "LDO OCP",
    11: "BAT UVLO",
    12: "Safety timer",
    13: "Watchdog",
    14: "IMAX open",
    15: "TS open",
  },
  
  [UnitId.MAX]: {},

  [UnitId.UNKNOWN]: {}, // Fallback for unknown unit
}
