/*
 * Copyright (C) 10XBETA - All Rights Reserved
 *
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 */

/**
 * @file imu.c
 * @ingroup imu_driver
 * @brief
 */

/***********************************************************************************************************************
 * Includes
 **********************************************************************************************************************/
// Standard includes
#include <stdbool.h>
#include <stdint.h>

// Custom includes
#include "../../../common/drivers/i2c/i2c_driver_interface.h"
#include "../../../common/modules/debug/debug.h"
#include "../../../common/result.h"
#include "imu.h"
#include "nrf_delay.h"

static const uint8_t THIS_UNIT_ID = (uint8_t)SW_UNIT_ID_IMU_DRV;

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
#define TWI_DELAY_MS            (10u)
#define I2C_TIMEOUT_US_PER_BYTE (1000u) /// For 400kHz frequencey with 40x safety factor

// The BMI323 IMU datasheet (revision V1.4) used as the source for all register values and addresses
// https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bmi323-ds000.pdf

// Register addresses are prefixed with REG_
// Pre-calculated configurations are prefixed with CFG_
// Values intended for the extended register space will contain _ER after the prefix

// IMU device address
#define REG_I2C_ADDR    (0x68)
#define REG_CHIP_ID_VAL (0x0043)

// IMU register addresses
#define REG_CHIP_ID    (0x00) // CHIP ID register
#define REG_ERROR      (0x01) // Error status flags
#define REG_STATUS     (0x02) // Sensor status flags
#define REG_ACC_DATA_X (0x03) // ACC Data X.
#define REG_ACC_DATA_Y (0x04) // ACC Data Y.
#define REG_ACC_DATA_Z (0x05) // ACC Data Z.
#define REG_GYR_DATA_X (0x06) // GYR Data X.
#define REG_GYR_DATA_Y (0x07) // GYR Data Y.
#define REG_GYR_DATA_Z (0x08) // GYR Data Z.
#define REG_TEMP_DATA  (0x09) // Temperature data

#define REG_FEAT_IO_0 (0x10)
#define CFG_FEAT_IO_0 (0x7400) // All taps and significant motion enabled

#define REG_FEAT_IO_1   (0x11)
#define REG_FEAT_IO_2   (0x12)
#define REG_FEAT_IO_3   (0x13)
#define REG_FEAT_STATUS (0x14)
#define REG_FEAT_CTRL   (0x40)

#define CFG_FEAT_IO_2       (0x012C)
#define VAL_FEAT_ENG_ACTIVE (0x0001)

#define REG_IMU_ACC (0x20) // IMU Accelerometer config register
#define REG_IMU_GYR (0x21) // IMU gyroscope config register
#define REG_IMU_CMD (0x7E) // IMU command register

#define REG_INT_MAP1 (0x3A)
#define REG_INT_MAP2 (0x3B)
#define REG_INT_CONF (0x39)

#define CFG_INT_CONF (0x0001) // Configure interrupts to be latching
#define CFG_INT_MAP1 (0x1000) // MAP Significant motion to INT1 pin
#define CFG_INT_MAP2                                                                                                   \
   (0x2001) // MAP All TAP to INT1 pin and fifo watermark to INT2 pin
            // Sig Mot and TAP are generated by feature engine.
            // The datasheet recommends separating feature engine interrupts
            // from non-feature engine based interrupts to avoid race conditions
            // Datasheet page 50

// Interrupt status registers and masks
#define REG_INT_STATUS1 (0x0D)
#define REG_INT_STATUS2 (0x0E)

#define SIG_MOT_INTERRUPT_MASK (0x0040)
#define TAP_INTERRUPT_MASK     (0x0100)
#define FIFO_WM_INTERRUPT_MASK (0x4000)
#define SINGLE_TAP_MASK        (0x0008)
#define DOUBLE_TAP_MASK        (0x0010)
#define TRIPLE_TAP_MASK        (0x0020)

#define CFG_MODE_DISABLE (0x0000)
#define CFG_MODE_ACTIVE  (0x7000) // Sig mot requires high performance mode at low sample rates

#define CFG__1_SAMPLE_AVG (0x0000)
#define CFG__2_SAMPLE_AVG (0x0100)
#define CFG__4_SAMPLE_AVG (0x0200)
#define CFG__8_SAMPLE_AVG (0x0300)
#define CFG_16_SAMPLE_AVG (0x0400)
#define CFG_32_SAMPLE_AVG (0x0500)
#define CFG_64_SAMPLE_AVG (0x0600)

#define CFG_RANGE_1 (0x0000)
#define CFG_RANGE_2 (0x0010)
#define CFG_RANGE_3 (0x0020)
#define CFG_RANGE_4 (0x0030)

#define REG_FEAT_EXT (0x47)

#define CFG_BW_SAMPLE_RATE__0_5 (0x0000)
#define CFG_BW_SAMPLE_RATE_0_25 (0x0800)

#define CFG_SAMPLE_RATE_12_5HZ (0x0005) // Subset of available options
#define CFG_SAMPLE_RATE__25HZ  (0x0006)
#define CFG_SAMPLE_RATE__50HZ  (0x0007)
#define CFG_SAMPLE_RATE_100HZ  (0x0008)

// Select and configure the active sampling rate
#if IMU_ACTIVE_SAMPLING_RATE_HZ == 12
#   define CFG_SAMPLE_RATE_ACTIVE CFG_SAMPLE_RATE_12_5HZ
#elif IMU_ACTIVE_SAMPLING_RATE_HZ == 25
#   define CFG_SAMPLE_RATE_ACTIVE CFG_SAMPLE_RATE__25HZ
#elif IMU_ACTIVE_SAMPLING_RATE_HZ == 50
#   define CFG_SAMPLE_RATE_ACTIVE CFG_SAMPLE_RATE__50HZ
#elif IMU_ACTIVE_SAMPLING_RATE_HZ == 100
#   define CFG_SAMPLE_RATE_ACTIVE CFG_SAMPLE_RATE_100HZ
#else
#   error "IMU_ACTIVE_SAMPLING_RATE_HZ is set to an unsupported value. " \
        "Supported values are 12 (for 12.5 Hz), 25, 50, and 100."
#endif

#define CFG_ACTIVE_STATE                                                                                               \
   (CFG_MODE_ACTIVE | CFG__1_SAMPLE_AVG | CFG_RANGE_1 | CFG_BW_SAMPLE_RATE__0_5 | CFG_SAMPLE_RATE_ACTIVE)
#define CFG_DORMANT_STATE                                                                                              \
   (CFG_MODE_DISABLE | CFG__1_SAMPLE_AVG | CFG_RANGE_1 | CFG_BW_SAMPLE_RATE__0_5 | CFG_SAMPLE_RATE_12_5HZ)

#define CFG_SOFT_RESET (0xDEAF)

// FIFO Buffer registers and configurations
#define REG_FIFO_WM    (0x35)
#define REG_FIFO_CONF  (0x36)
#define REG_FIFO_CTRL  (0x37) // setting bit 0 flushes the fifo
#define REG_FIFO_LEVEL (0x15)
#define REG_FIFO_DATA  (0x16)

#define CFG_FIFO_WM (uint16_t)(512u) // Level in words at which to raise the fifo WM interrupt

#define CFG_FIFO_CONF                                                                                                  \
   (0x0700) // Enable data buffering for accelerometer, gyro, and time
            // Temp excluded because defaults to 50Hz writes in the selected modes
            // and causes the fifo to fill too quickly

// This section contains register addresses and configurations for the feature engine extended register space
#define REG_ER_TAP_1 (0x1E)
#define CFG_ER_TAP_1 (0x0076) // Configure tap to be mostly in the z axis. All other settings are defaults

#define REG_ER_SIG_MOT1 (0x0D)
#define REG_ER_SIG_MOT2 (0x0E)
#define REG_ER_SIG_MOT3 (0x0F)

// Significant motion tuning
#define CFG_ER_PK_PK_MIN (uint16_t)(15) // 10 bits  - Minimum peak to peak acceleration magnitude - 0 to 1023
#define CFG_ER_MCR_MIN   (uint16_t)(4)  // 6 bits   - Minimum mean crossing rate - 0 to 63

#define CFG_ER_PK_PK_MAX (uint16_t)(500) // 10 bits  - Maximum peak to peak acceleration magnitude - 0 to 1023
#define CFG_ER_MCR_MAX   (uint16_t)(17)  // 6 bits   - Maximum mean crossing rate - 0 to 63

#define CFG_ER_SIG_MOT1 (uint16_t)(100) // Block size - 0 to 65535
#define CFG_ER_SIG_MOT2 ((CFG_ER_MCR_MIN << 10) & 0xFA00) & (CFG_ER_PK_PK_MIN & 0x03FF)
#define CFG_ER_SIG_MOT3 ((CFG_ER_MCR_MIN << 10) & 0xFA00) & (CFG_ER_PK_PK_MAX & 0x03FF)

// Frequently used bit Masks
#define MSK_LAST_BIT    (0x0001)
#define MSK_LAST_NIBBLE (0x000F)
#define MSK_LAST_BYTE   (0x00FF)
#define MSK_ALL_BYTES   (0xFFFF)

// Constants
#define TEMP_SCALE_LSB_PER_K (512u) // As per page 73 of IMU datasheet
#define TEMP_OFFSET          (23u)
#define STARTUP_DELAY_MS     (35u) // Power on + reset + startup delay as per ppp 8 and 10

// Acceleration is given in in the range -2G to +2G scaled to fit an int16_t
#define SCALE_FACTOR_LSB_PER_G  (int16_t)(16384)
#define GRAVITY_IN_MM_PER_S_SQR (int16_t)(9810)

#define TO_DECI_DEGREES_PER_S (int16_t)(10)
#define LSB_DECI_DEGREE_PER_S (int16_t)(2644)

/***********************************************************************************************************************
 * Types
 **********************************************************************************************************************/
typedef enum
{
   IMU_I2C_STAT_OK = 0,
   IMU_I2C_STAT_TX_ERR,
   IMU_I2C_STAT_RX_ERR,
   IMU_I2C_STAT_MAX
} IMU_I2C_STAT;

typedef enum
{
   TWI_STAT_OK = 0,
   TWI_STAT_ERR,
   TWI_STAT_MAX
} TWI_STAT;

typedef struct __attribute__((packed, aligned(1)))
{
   uint16_t padding_bytes;
   imu_data_entry_t entry;
} padded_imu_data_entry_t;

typedef struct __attribute__((packed, aligned(1)))
{
   uint16_t padding_bytes;
   uint16_t data;
} imu_reg_read_t;

typedef struct __attribute__((packed, aligned(1)))
{
   uint8_t address;
   uint16_t data;
} imu_reg_write_t;

typedef struct __attribute__((packed, aligned(1)))
{
   uint8_t feat_address;
   uint8_t config_address;
   uint16_t config_data;
} imu_feat_reg_write_t;

typedef struct __attribute__((packed, aligned(1)))
{
   uint16_t padding_bytes;
   imu_data_entry_t data;
} imu_entry_read_t;

/***********************************************************************************************************************
 * Static function declarations
 **********************************************************************************************************************/
// Interface functions
static result_t get_temperature_celsius(const imu_interface_t *const interface, int16_t *temperature_celsius);
static result_t set_state(const imu_interface_t *const interface, IMU_STATE state);
static result_t get_state(const imu_interface_t *const interface, IMU_STATE *state);
static result_t get_interrupts(const imu_interface_t *const interface, imu_interrupt_map_t *map);
static result_t get_imu_data_entry_count(const imu_interface_t *const interface, uint16_t *count);
static result_t clear_imu_data(const imu_interface_t *const interface);
static result_t get_imu_data_entries(const imu_interface_t *const interface, uint16_t count, imu_data_entry_t *entries);
static result_t get_imu_data_entry(const imu_interface_t *const interface, imu_data_entry_t *entry);

// Internal functions
static result_t imu_chip_init(void);
static result_t imu_interrupt_init(void);
static result_t imu_feature_engine_init(void);
static result_t imu_fifo_init(void);
static result_t imu_apply_state_dormant(void);
static result_t imu_apply_state_active(void);
static result_t imu_apply_state_uninitialized(void);

static result_t imu_feat_reg_write(uint8_t i2c_address, uint8_t feat_address, uint8_t config_address, uint16_t data);
static result_t imu_reg_write(uint8_t i2c_address, uint8_t register_address, uint16_t data);

static result_t imu_reg_read(uint8_t i2c_address, uint8_t register_address, uint16_t *data, uint16_t mask);
static result_t imu_entry_read(uint8_t i2c_address, uint8_t register_address, imu_data_entry_t *entry);
/***********************************************************************************************************************
 * Variables
 **********************************************************************************************************************/
static i2c_driver_interface_t *mp_i2c_driver_interface;
/***********************************************************************************************************************
 * Global function definitions
 **********************************************************************************************************************/
result_t imu_x_init(imu_t *const self, i2c_driver_interface_t *i2c_interface)
{
   RETURN_ERR_IF_NULL(self, IMU_ERROR_PTR_NULL);
   RETURN_ERR_IF_INTERFACE_NULL(i2c_interface, IMU_ERROR_PTR_NULL);

   self->interface.parent = self; // Connect the interface with the containing unit instance to allow being able to
   // reference internal state variables.

   // Prevent attempted re-init of initialized IMU
   RETURN_ERR_IF_TRUE(IMU_STATE_UNINITIALIZED != self->_state, IMU_ERROR_ALREADY_INITIALIZED);

   self->interface.get_temperature_celsius
      = get_temperature_celsius; // Map static functions to those exposed in the interface
   self->interface.get_state = get_state;
   self->interface.set_state = set_state;
   self->interface.get_interrupts = get_interrupts;
   self->interface.get_imu_data_entry_count = get_imu_data_entry_count;
   self->interface.clear_imu_data = clear_imu_data;
   self->interface.get_imu_data_entries = get_imu_data_entries;
   self->interface.get_imu_data_entry = get_imu_data_entry;
   mp_i2c_driver_interface = i2c_interface;

   result_t result = imu_chip_init();                       // Initialize I2c interface to the IMU
   IF_OK_RUN_AND_UPDATE(result, imu_interrupt_init());      // Configure the interrupt register
   IF_OK_RUN_AND_UPDATE(result, imu_feature_engine_init()); // Initialize the feature engine

   self->_state = IMU_STATE_DORMANT;

   return result;
}

/***********************************************************************************************************************
 * Static function definitions
 **********************************************************************************************************************/
static result_t get_imu_data_entry_count(const imu_interface_t *const interface, uint16_t *count)
{
   RETURN_ERR_IF_INTERFACE_NULL(interface, IMU_ERROR_PTR_NULL);
   RETURN_ERR_IF_NULL(count, IMU_ERROR_PTR_NULL);
   uint16_t words_in_fifo = 0;

   result_t result = imu_reg_read(REG_I2C_ADDR, REG_FIFO_LEVEL, &words_in_fifo, 0x07FF);

   if(IS_OK(result))
   {
      // Multiply fifo words by 2 to get bytes and divide by frames size to get frame count
      *count = (uint16_t)(words_in_fifo * 2u / sizeof(imu_data_entry_t));
   }

   return result;
}

static result_t clear_imu_data(const imu_interface_t *const interface)
{
   RETURN_ERR_IF_INTERFACE_NULL(interface, IMU_ERROR_PTR_NULL);
   return imu_reg_write(REG_I2C_ADDR, REG_FIFO_CTRL, 0x0001);
}

static result_t get_imu_data_entries(const imu_interface_t *const interface, uint16_t count, imu_data_entry_t *entries)
{
   RETURN_ERR_IF_INTERFACE_NULL(interface, IMU_ERROR_PTR_NULL);
   RETURN_ERR_IF_NULL(entries, IMU_ERROR_PTR_NULL);

   result_t result = RESULT_OK;
   uint16_t available_entries = 0;

   // Check that we aren't reading more data entries than are available
   result = get_imu_data_entry_count(interface, &available_entries);

   if((count > available_entries) && IS_OK(result))
   {
      SET_ERR(result, IMU_ERROR_INVALID_ARG);
   }

   imu_data_entry_t rx_entry = {0};

   // Read count number of data entries from the fifo data register
   for(int index = 0; index < count; index++)
   {
      IF_OK_RUN_AND_UPDATE(result, imu_entry_read(REG_I2C_ADDR, REG_FIFO_DATA, &rx_entry));
      BREAK_ON_ERR(result);

      // Convert to mm/s^2
      rx_entry.acc_x_axis = (int16_t)(rx_entry.acc_x_axis * GRAVITY_IN_MM_PER_S_SQR / SCALE_FACTOR_LSB_PER_G);
      rx_entry.acc_y_axis = (int16_t)(rx_entry.acc_y_axis * GRAVITY_IN_MM_PER_S_SQR / SCALE_FACTOR_LSB_PER_G);
      rx_entry.acc_z_axis = (int16_t)(rx_entry.acc_z_axis * GRAVITY_IN_MM_PER_S_SQR / SCALE_FACTOR_LSB_PER_G);

      rx_entry.angular_rate_x_axis
         = (int16_t)(rx_entry.angular_rate_x_axis * TO_DECI_DEGREES_PER_S / LSB_DECI_DEGREE_PER_S);
      rx_entry.angular_rate_y_axis
         = (int16_t)(rx_entry.angular_rate_y_axis * TO_DECI_DEGREES_PER_S / LSB_DECI_DEGREE_PER_S);
      rx_entry.angular_rate_z_axis
         = (int16_t)(rx_entry.angular_rate_z_axis * TO_DECI_DEGREES_PER_S / LSB_DECI_DEGREE_PER_S);

      entries[index] = rx_entry;
   }

   // Read the status register containing the fifo interrupt to clear its status
   // The interrupt is latching can only be cleared by reading the register when the fifo is filled below the watermark.
   uint16_t int2_data = 0;
   IF_OK_RUN_AND_UPDATE(result, imu_reg_read(REG_I2C_ADDR, REG_INT_STATUS2, &int2_data, MSK_ALL_BYTES));

   return result;
}

static result_t get_imu_data_entry(const imu_interface_t *const interface, imu_data_entry_t *entry)
{
   RETURN_ERR_IF_INTERFACE_NULL(interface, IMU_ERROR_PTR_NULL);
   RETURN_ERR_IF_NULL(entry, IMU_ERROR_PTR_NULL);

   result_t result = RESULT_OK;
   uint16_t available_entries = 0;

   result = get_imu_data_entry_count(interface, &available_entries);

   if((0 == available_entries) && (IS_OK(result)))
   {
      SET_ERR(result, IMU_ERROR_NO_ENTRIES);
   }

   memset(entry, 0, sizeof(imu_data_entry_t));

   // Read the latest data entry and discard the rest
   for(uint16_t index = 0; index < available_entries; index++)
   {
      IF_OK_RUN_AND_UPDATE(result, imu_entry_read(REG_I2C_ADDR, REG_FIFO_DATA, entry));
      BREAK_ON_ERR(result);
      // Ignore values that we don't care to return
      if(index != available_entries - 1u)
      {
         continue;
      }

      // Convert to mm/s^2
      entry->acc_x_axis = (int16_t)(entry->acc_x_axis * GRAVITY_IN_MM_PER_S_SQR / SCALE_FACTOR_LSB_PER_G);
      entry->acc_y_axis = (int16_t)(entry->acc_y_axis * GRAVITY_IN_MM_PER_S_SQR / SCALE_FACTOR_LSB_PER_G);
      entry->acc_z_axis = (int16_t)(entry->acc_z_axis * GRAVITY_IN_MM_PER_S_SQR / SCALE_FACTOR_LSB_PER_G);

      entry->angular_rate_x_axis
         = (int16_t)(entry->angular_rate_x_axis * TO_DECI_DEGREES_PER_S / LSB_DECI_DEGREE_PER_S);
      entry->angular_rate_y_axis
         = (int16_t)(entry->angular_rate_y_axis * TO_DECI_DEGREES_PER_S / LSB_DECI_DEGREE_PER_S);
      entry->angular_rate_z_axis
         = (int16_t)(entry->angular_rate_z_axis * TO_DECI_DEGREES_PER_S / LSB_DECI_DEGREE_PER_S);
   }

   // Read the status register containing the fifo interrupt to clear its status
   // The interrupt is latching can only be cleared by reading the register when the fifo is filled below the watermark.
   uint16_t int2_data = 0;

   IF_OK_RUN_AND_UPDATE(result, imu_reg_read(REG_I2C_ADDR, REG_INT_STATUS2, &int2_data, MSK_ALL_BYTES));

   return result;
}

static result_t get_state(const imu_interface_t *const interface, IMU_STATE *state)
{
   RETURN_ERR_IF_INTERFACE_NULL(interface, IMU_ERROR_PTR_NULL);
   RETURN_ERR_IF_NULL(state, IMU_ERROR_PTR_NULL);
   result_t result = RESULT_OK;

   *state = interface->parent->_state;
   return result;
}

static result_t set_state(const imu_interface_t *const interface, IMU_STATE state)
{
   RETURN_ERR_IF_INTERFACE_NULL(interface, IMU_ERROR_PTR_NULL);

   result_t result = RESULT_OK;

   if(interface->parent->_state != state)
   {
      switch(state)
      {
         case IMU_STATE_DORMANT: // Sleep mode - Accelerometer, Gyroscope and temperature sensor off
            result = imu_apply_state_dormant();
            break;

         case IMU_STATE_ACTIVE: // High power - High performance mode
            result = imu_apply_state_active();
            break;

         case IMU_STATE_UNINITIALIZED: // Soft reset the IMU - device will need to be re-initialized before use
            result = imu_apply_state_uninitialized();
            break;
         case IMU_STATE_MAX:
         // Fall through
         default:
            SET_ERR(result, IMU_ERROR_INVALID_ARG);
            break;
      }

      if(IS_OK(result))
      {
         interface->parent->_state = state;
      }
   }

   return result;
}

static result_t get_temperature_celsius(const imu_interface_t *const interface, int16_t *temperature_celsius)
{
   RETURN_ERR_IF_INTERFACE_NULL(interface, IMU_ERROR_PTR_NULL);
   RETURN_ERR_IF_NULL(temperature_celsius, IMU_ERROR_PTR_NULL);
   result_t result = RESULT_OK;

   // Check if IMU is inactive
   if(IMU_STATE_ACTIVE != interface->parent->_state)
   {
      DEBUG_DEBUG("Attempted read data from the IMU when dormant");
      SET_ERR(result, IMU_ERROR_INVALID_STATE);
   }

   uint16_t raw_data = 0;

   IF_OK_RUN_AND_UPDATE(result, imu_reg_read(REG_I2C_ADDR, REG_TEMP_DATA, &raw_data, MSK_ALL_BYTES));

   if(IS_OK(result))
   {
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wsign-conversion"
#pragma GCC diagnostic ignored "-Wconversion"
      *temperature_celsius = (int16_t)raw_data / TEMP_SCALE_LSB_PER_K + TEMP_OFFSET; // Cast is safe because the data is
                                                                                     // already in 2's complement
#pragma GCC diagnostic pop
   }

   return result;
}

static result_t get_interrupts(const imu_interface_t *const interface, imu_interrupt_map_t *map)
{
   RETURN_ERR_IF_INTERFACE_NULL(interface, IMU_ERROR_PTR_NULL);
   RETURN_ERR_IF_NULL(map, IMU_ERROR_PTR_NULL);
   // Check if IMU is inactive
   if(IMU_STATE_ACTIVE != interface->parent->_state)
   {
      DEBUG_DEBUG("Attempted read data from the IMU when dormant");
      RETURN_ERR(IMU_ERROR_INVALID_STATE);
   }

   uint16_t int1_data = 0;
   uint16_t int2_data = 0;
   uint16_t feat_reg = 0;
   bool tap_detected = false;
   imu_interrupt_map_t local_map = {0};
   result_t result = RESULT_OK;

   result = imu_reg_read(REG_I2C_ADDR, REG_INT_STATUS1, &int1_data, MSK_ALL_BYTES);
   IF_OK_RUN_AND_UPDATE(result, imu_reg_read(REG_I2C_ADDR, REG_INT_STATUS2, &int2_data, MSK_ALL_BYTES));
   // Read feature engine register for info on which type of tap was detected
   IF_OK_RUN_AND_UPDATE(result, imu_reg_read(REG_I2C_ADDR, REG_FEAT_EXT, &feat_reg, MSK_ALL_BYTES));

   if(IS_OK(result))
   {
      // Check for and assign Significant motion and fifo limit interrupts
      local_map.sig_motion = SIG_MOT_INTERRUPT_MASK == (SIG_MOT_INTERRUPT_MASK & int1_data);
      local_map.limited_data_storage_remaining = FIFO_WM_INTERRUPT_MASK == (FIFO_WM_INTERRUPT_MASK & int2_data);

      // Check if there was a tap detected, then assign the correct type from the feat ext register
      tap_detected = TAP_INTERRUPT_MASK == (TAP_INTERRUPT_MASK & int1_data);

      local_map.single_tap = tap_detected && (SINGLE_TAP_MASK == (SINGLE_TAP_MASK & feat_reg));
      local_map.double_tap = tap_detected && (DOUBLE_TAP_MASK == (DOUBLE_TAP_MASK & feat_reg));
      local_map.triple_tap = tap_detected && (TRIPLE_TAP_MASK == (TRIPLE_TAP_MASK & feat_reg));

      *map = local_map; // Update the interrupt map
   }

   return result;
}

/**
 * @brief Function to init the IMU fifo
 *
 * Enables data write to the fifo and sets the level at which the fifo watermark is triggered
 *
 * @return A boolean indicating if the operation was successful
 */
static result_t imu_fifo_init(void)
{
   result_t result = RESULT_OK;

   result = imu_reg_write(REG_I2C_ADDR, REG_FIFO_WM, CFG_FIFO_WM);
   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_FIFO_CONF, CFG_FIFO_CONF));
   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_FIFO_CTRL, MSK_LAST_BIT));

   return result;
}

/**
 * @brief Function to place IMU in active mode
 *
 * Updates accelerometer and gyroscope to values that will place IMU in a high performance, high power state
 *
 * @return A boolean indicating if the operation was successful
 */
static result_t imu_apply_state_active(void)
{
   result_t result = RESULT_OK;

   result = imu_reg_write(REG_I2C_ADDR, REG_IMU_ACC, CFG_ACTIVE_STATE);
   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_IMU_GYR, CFG_ACTIVE_STATE));

   if(IS_OK(result))
   {
      nrf_delay_ms(STARTUP_DELAY_MS); // Startup delay while the gyro and accelerometers start up
   }

   IF_OK_RUN_AND_UPDATE(result, imu_fifo_init()); // Initialize the fifo buffer

   // Configure the feature engine
   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_FEAT_IO_0, CFG_FEAT_IO_0)); // Send configuration
   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_FEAT_STATUS, 0x0001));      // Apply configuration

   return result;
}

/**
 * @brief Function to soft reset the IMU, placing it in uninitialized mode
 *
 * @return A boolean indicating if the operation was successful
 */
static result_t imu_apply_state_uninitialized()
{
   result_t result = imu_reg_write(REG_I2C_ADDR, REG_IMU_CMD, CFG_SOFT_RESET); // Send the soft reset command

   if(IS_OK(result))
   {
      nrf_delay_ms(STARTUP_DELAY_MS);
   }

   return result;
}

/**
 * @brief Function to place IMU in dormant mode
 *
 * Updates accelerometer and gyroscope to values that will place IMU in a low power state
 *
 * @return A boolean indicating if the operation was successful
 */
static result_t imu_apply_state_dormant()
{
   result_t result
      = imu_reg_write(REG_I2C_ADDR, REG_IMU_ACC, CFG_DORMANT_STATE); // Update accelerometer config to values
                                                                     // appropriate for the desired mode

   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_IMU_GYR, CFG_DORMANT_STATE));

   return result;
}

/**
 * @brief Function to initialize the feature engine
 *
 * Initializes the feature engine as described on page 29 of the IMU datasheet
 *
 *
 * @return A boolean indicating if the feature engine was started successfully
 */
static result_t imu_feature_engine_init()
{
   result_t result = RESULT_OK;

   // Enable the Feature engine
   result = imu_reg_write(REG_I2C_ADDR, REG_FEAT_IO_2, CFG_FEAT_IO_2);
   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_FEAT_STATUS, MSK_LAST_BIT));
   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_FEAT_CTRL, MSK_LAST_BIT));

   if(IS_OK(result))
   {
      DEBUG_DEBUG("Feature engine turned on.");
      // Configure Tap axis and significant motion sensitivity in the feature engine external address space
      result = imu_feat_reg_write(REG_I2C_ADDR, REG_FEAT_EXT, REG_ER_SIG_MOT1, CFG_ER_SIG_MOT1);
   }

   IF_OK_RUN_AND_UPDATE(result, imu_feat_reg_write(REG_I2C_ADDR, REG_FEAT_EXT, REG_ER_SIG_MOT2, CFG_ER_SIG_MOT2));
   IF_OK_RUN_AND_UPDATE(result, imu_feat_reg_write(REG_I2C_ADDR, REG_FEAT_EXT, REG_ER_SIG_MOT3, CFG_ER_SIG_MOT3));
   IF_OK_RUN_AND_UPDATE(result, imu_feat_reg_write(REG_I2C_ADDR, REG_FEAT_EXT, REG_ER_TAP_1, CFG_ER_TAP_1));

   if(IS_OK(result))
   {
      DEBUG_DEBUG("Tap axis and significant motion sensitivity configured.");

      // Poll for feature activated status
      const uint16_t timeout_ms = 5u;
      const uint16_t max_timeout_ms = 20u;
      uint16_t data;
      SET_ERR(result, IMU_ERROR_INIT_FAILURE);

      for(uint16_t elapsed_ms = 0; elapsed_ms < max_timeout_ms; elapsed_ms += timeout_ms)
      {
         nrf_delay_ms(timeout_ms);

         result = imu_reg_read(REG_I2C_ADDR, REG_FEAT_IO_1, &data, MSK_LAST_NIBBLE); // Read the error status bits of
         if((IS_OK(result)) && (VAL_FEAT_ENG_ACTIVE == data))                        // the feat. engine IO1 reg for
         {                                                                           // Feature engine activated status
            CLEAR_ERR(result);
            break;
         }
      }
   }

   return result;
}

/**
 * @brief Function to initialize the interrupts on the IMU
 *
 * Configures the interrupts on the IMU. MAP Significant motion and all gestures to pin1 and
 * fifo watermark to INT2 pin
 *
 * @return An boolean indicating if the interrupts were configured successfully
 */
static result_t imu_interrupt_init(void)
{
   result_t result = imu_reg_write(REG_I2C_ADDR, REG_INT_MAP1, CFG_INT_MAP1); // Send configuration

   // Set interrupt behaviour to latching
   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_INT_CONF, CFG_INT_CONF));

   // Apply configuration
   IF_OK_RUN_AND_UPDATE(result, imu_reg_write(REG_I2C_ADDR, REG_INT_MAP2, CFG_INT_MAP2));

   return result;
}

/**
 * @brief Function that initializes the I2c interface on the IMU
 *
 * Initilizes and confirms successful I2c comms to correct IMU by reading and confirming chip ID
 *
 * @return boolean indicating whether chip read was successful
 */
static result_t imu_chip_init(void)
{
   uint16_t chip_id = 0;

   // Read the IMU chip ID to confirm i2c Comms are up
   result_t result = imu_reg_read(REG_I2C_ADDR, REG_CHIP_ID, &chip_id, MSK_LAST_BYTE);

   if((REG_CHIP_ID_VAL != chip_id) && IS_OK(result))
   {
      DEBUG_DEBUG("Incorrect CHIP ID. Expected: 0x%x Received: 0x%x", REG_CHIP_ID_VAL, chip_id);
      SET_ERR(result, IMU_ERROR_INIT_FAILURE);
   }
   return result;
}

/**
 * @brief Reads data from the IMU via I2c
 *
 * Translates between the 16bit wide registers used by the IMu and the 8 bit register addresses
 *
 * Assumes a single 16bit wide value is requested.
 *
 * @param i2c_address      - Address of the IMU on the I2c bus
 * @param register_address - Register address that will be read from
 * @param data             - Address to 16bits of memory that the data will be written to
 * @param mask             - mask for the data if only specific bits are required
 *
 * @return enum indicating whether the read was successful
 */
static result_t imu_reg_read(uint8_t i2c_address, uint8_t register_address, uint16_t *data, uint16_t mask)
{
   result_t result = RESULT_OK;

   uint8_t bytes = sizeof(register_address);
   uint32_t wait_us = I2C_TIMEOUT_US_PER_BYTE * sizeof(register_address);

   result = mp_i2c_driver_interface->transmit(mp_i2c_driver_interface, i2c_address, &register_address, bytes, wait_us);

   UPDATE_ERR(result, IMU_ERROR_I2C_ERROR);

   if(IS_OK(result))
   {
      imu_reg_read_t rx_data = {0};

      bytes = sizeof(rx_data);
      wait_us = I2C_TIMEOUT_US_PER_BYTE * sizeof(rx_data);

      result = mp_i2c_driver_interface->receive(
         mp_i2c_driver_interface, i2c_address, ((uint8_t *)&rx_data), bytes, wait_us);

      UPDATE_ERR(result, IMU_ERROR_I2C_ERROR);

      if(IS_OK(result))
      {
         // The IMU returns two dummy bytes when doing I2C reads so ignore the first uint16_t
         *data = mask & rx_data.data; // Mask the second uint16_t to get only the desired bits
      }
   }

   return result;
}

/**
 * @brief Reads data from the IMU via I2c
 *
 * Translates between the 16bit wide registers used by the IMu and the 8 bit register addresses
 *
 *
 * @param i2c_address      - Address of the IMU on the I2c bus
 * @param register_address - Register address that will be read from
 * @param entry            - Address that the entry that the data will be written to
 *
 * @return enum indicating whether the read was successful
 */
static result_t imu_entry_read(uint8_t i2c_address, uint8_t register_address, imu_data_entry_t *entry)
{
   result_t result = RESULT_OK;

   uint8_t bytes = sizeof(register_address);
   uint32_t wait_us = I2C_TIMEOUT_US_PER_BYTE * sizeof(register_address);

   result = mp_i2c_driver_interface->transmit(mp_i2c_driver_interface, i2c_address, &register_address, bytes, wait_us);

   UPDATE_ERR(result, IMU_ERROR_I2C_ERROR);

   if(IS_OK(result))
   {
      imu_entry_read_t rx_data = {0};

      bytes = sizeof(rx_data);
      wait_us = I2C_TIMEOUT_US_PER_BYTE * sizeof(rx_data);

      result = mp_i2c_driver_interface->receive(
         mp_i2c_driver_interface, i2c_address, ((uint8_t *)&rx_data), bytes, wait_us);

      UPDATE_ERR(result, IMU_ERROR_I2C_ERROR);

      if(IS_OK(result))
      {
         *entry = rx_data.data;
      }
   }

   return result;
}

/**
 * @brief Writes data to an IMU register via I2c
 *
 * Translates between the 16bit wide registers used by the IMu and the 8 bit register addresses
 *
 * Facilitates less verbose code when setting single registers
 *
 * @param i2c_address      - Address of the IMU on the I2c bus
 * @param register_address - Register address that will be written to
 * @param data             - Data that will be written to the address
 *
 * @return indication whether the write was successful
 */
static result_t imu_reg_write(uint8_t i2c_address, uint8_t register_address, uint16_t data)
{
   imu_reg_write_t tx_data = {0};

   // Write the register address and data into transmit buffer
   tx_data.address = register_address; // Address is 8 bit wide
   tx_data.data = data;

   uint8_t bytes = sizeof(tx_data);
   uint32_t wait_us = I2C_TIMEOUT_US_PER_BYTE * sizeof(tx_data);

   // Transmit the data over TWI Bus
   result_t result
      = mp_i2c_driver_interface->transmit(mp_i2c_driver_interface, i2c_address, ((uint8_t *)&tx_data), bytes, wait_us);

   UPDATE_ERR(result, IMU_ERROR_I2C_ERROR);

   if(IS_OK(result))
   {
      nrf_delay_ms(TWI_DELAY_MS);
   }

   return result;
}

/**
 * @brief Writes data to the feature engine in the IMU via I2c
 *
 * Translates between the 16bit wide registers used by the IMu and the 8 bit register addresses
 *
 * @param i2c_address      - Address of the IMU on the I2c bus
 * @param feat_address     - Feature config address on the IMU
 * @param config_address   - Address of the specific config register within the feature engine
 * @param data             - Data that will be written to the address
 *
 * @return enum indicating whether the write was successful
 */
static result_t imu_feat_reg_write(uint8_t i2c_address, uint8_t feat_address, uint8_t config_address, uint16_t data)
{
   imu_feat_reg_write_t tx_data = {0};

   tx_data.feat_address = feat_address;
   tx_data.config_address = config_address;
   tx_data.config_data = data;

   uint8_t bytes = sizeof(tx_data);
   uint32_t wait_us = I2C_TIMEOUT_US_PER_BYTE * sizeof(tx_data);

   // Transmit the data over TWI Bus
   result_t result
      = mp_i2c_driver_interface->transmit(mp_i2c_driver_interface, i2c_address, ((uint8_t *)&tx_data), bytes, wait_us);

   UPDATE_ERR(result, IMU_ERROR_I2C_ERROR);

   if(IS_OK(result))
   {
      nrf_delay_ms(TWI_DELAY_MS);
   }
   return result;
}